### ISSUE TITLE
awslabs/tough is incompatible with new root-signing

### ISSUE THREAD

**Issue by jku** [sigstore/root-signing#1167]
#1164 starts using "ecdsa" as the keytype as the specification now suggests.

This seems to break awslabs/tough: https://github.com/awslabs/tough/issues/754
`Failed to load repository: Failed to parse root metadata: Invalid SubjectPublicKeyInfo document at line 18 column 4`

@kommendorkapten plans to disable the tough test for now: let's re-enable when possible

**Comment by Hayden-IO** [comment]
This is now done.
