### ISSUE TITLE
Upcoming keyholder rotation!

### ISSUE THREAD

**Issue by bobcallaway** [sigstore/root-signing#120]
@mnm678 @SantiagoTorres @dlorenc @lukehinds @bobcallaway 
CC: @asraa @haydentherapper 

Hi fellow keyholders!

We're approaching the time where we need to rotate key holders on the sigstore public TUF root, so there a couple of things we need to pull together to prepare:
* Deciding who rotates off
* Establishing guidelines for the set of keyholders
* Who we propose to add in this rotation

**_We should target to select a new keyholder and perform the rotation by March 15th._** Please give your feedback on the process, proposed policies, and any ideas to make this more fun / exciting 😄  

## Who rotates off?

We need to select one of the 5 of us to step down; if anyone would like to volunteer, please reply all and let the group know and we will skip this process this time; however, feedback is appreciated a more general process as described below:

At a sigstore community meeting, we will have a community member (not a keyholder) share their screen and use a RNG to pick a number between 1 and 5. The number selected will corresponding to the current list of keyholders sorted in dictionary order by keyID:

Current list for example:

@dlorenc: `2f64fb5eac0cf94dd39bb45308b98920055e9a0d8e012a7220787834c60aef97`
@lukehinds: `bdde902f5ec668179ff5ca0dabf7657109287d690bf97e230c21d65f99155c62`
@mnm678: `eaf22372f417dd618a46f6c627dbc276e9fd30a004fc94f9be946e73f8bd090b`
@SantiagoTorres: `f40f32044071a9365505da3d1e3be6561f6f22d0e60cf51df783999f6c3429cb`
@bobcallaway: `f505595165a177a41750a8e864ed1719b1edfccd5a426fd2c0ffda33ce7ff209`

The person selected will be the lucky(?) person who will rotate off this time. 

## Proposed guidelines for keyholders (feedback welcome!)
Terms: 
* `T`: threshold for the root TUF role

### MUST

* No more than `T-1` keyholders can be employed by the same company (including subsidiaries) at the same time 
  * Any change in employment or acquisition/merger that causes the current set of keyholders to be in violation of this rule must be rectified within 14 days
* At least 1 member of the sigstore Technical Advisory Council @sigstore/core-team must always be a keyholder

### SHOULD

* We should aim for keyholders to be geographically distributed 
* We should aim for keyholders to be representative of our diverse community
  * New (but engaged) community members
  * Those from underrepresented populations
  * Those who work or study in academic settings

**Comment by Hayden-IO** [comment]
How do we pick a new keyholder? Should it be decided by the members of the TAC? TAC plus the current keyholders? We also could ask for members of the community to self-nominate, but I don't want this to become too process-heavy (how then do we decide on a keyholder if there's many nominations? Vote? TAC?).

**Comment by dlorenc** [comment]
> How do we pick a new keyholder? Should it be decided by the members of the TAC? TAC plus the current keyholders? We also could ask for members of the community to self-nominate, but I don't want this to become too process-heavy (how then do we decide on a keyholder if there's many nominations? Vote? TAC?).

Maybe self-nominations, then let the existing key holders choose/vote out of them. That way they can help ensure the representation/geographic diversity goals.

**Comment by cpanato** [comment]
I would like to nominate myself :)

are we planning to open an issue and people nominate/self-nominate?

**Comment by lukehinds** [comment]
If it goes too random and it's one of the holders from the academic world, then we should really get someone from that sector rotated in.

The other factor we might want to consider is having vendor diversity, I don't know if we would get a set of 3 different vendors like we have now, but we should do our best to achieve this if we can, or at least close to it. #EDIT can see Dan already highlighted this point.

**Comment by joshuagl** [comment]
Not sure I meet enough criteria, but would like to nominate myself.

**Comment by dlorenc** [comment]
> If it goes too random and it's one of the holders from the academic world, then we should really get someone from that sector rotated in.

Yeah, this is why I think it's best to let the existing keyholders use a bit of discretion in picking out of the nominees.

**Comment by elfotografo007** [comment]
I vote for @joshuagl

**Comment by bobcallaway** [comment]
On today's community call, @SantiagoTorres was the (un)lucky keyholder selected to rotate off this cycle.

**Comment by lukehinds** [comment]
> On today's community call, @SantiagoTorres was the (un)lucky keyholder selected to rotate off this cycle.

And further to this, it should be a replacement from the academic world.

**Comment by SantiagoTorres** [comment]
That's unfortunate. How many academics do we have on the list right now?

**Comment by lukehinds** [comment]
> That's unfortunate. How many academics do we have on the list right now?

Just Marina, minus yourself.

**Comment by SantiagoTorres** [comment]
I'm a little surprised this vote came in today to be quite honest. I knew it was coming in a community meeting, but not this one

**Comment by asraa** [comment]
> I'm a little surprised this vote came in today to be quite honest. I knew it was coming in a community meeting, but not this one

It was a random selection, btw! We do not want you to go :/

**Comment by SantiagoTorres** [comment]
Haha no, I understand! I just would've liked it to be there...

**Comment by lukehinds** [comment]
> > I'm a little surprised this vote came in today to be quite honest. I knew it was coming in a community meeting, but not this one
> 
> It was a random selection, btw! We do not want you to go :/

yep, it was a random generator with a range of 5, not a vote.

**Comment by SantiagoTorres** [comment]
Either way, how shall we proceed. I believe my bit is a NOOP or do I need to sign part of the rotation?

**Comment by asraa** [comment]
> Either way, how shall we proceed. I believe my bit is a NOOP or do I need to sign part of the rotation?

Your signature would be a valid sign as part of the sign off on the new keyholders (but since we only need 3 as a threshold you don't need to, since there's 3 overlapping). So totally up to you! 

I think we need more academic nominees :)

**Comment by SantiagoTorres** [comment]
Got it! I think even if symbolic it'd be nice if I signed off. I'll also try to find and push an academic in the community to nominate themselves :)

**Comment by trishankatdatadog** [comment]
Do I count as an academic or is too late? 😂 I was thinking of adding Datadog to list of orgs/companies involved in collaborating with sigstore, especially considering our work on go-tuf.

If it's not kosher, either @cpanato or @joshuagl sound like fine candidates to me!

P.S. If it helps, I already have a YubiKey with 4096-bit RSA GPG key on it, so might help with cryptographic diversity...

**Comment by lukehinds** [comment]
> Do I count as an academic or is too late? 😂 I was thinking of adding Datadog to list of orgs/companies involved in collaborating with sigstore, especially considering our work on go-tuf.
> 
> If it's not kosher, either @cpanato or @joshuagl sound like fine candidates to me!
> 
> P.S. If it helps, I already have a YubiKey with 4096-bit RSA GPG key on it, so might help with cryptographic diversity...

I actually nominated you out loud on the community call , and then realised seconds later you have graduated!

To the rest of the thread, would we be open to an academic who has yet to contribute? I was thinking of someone like Justin Cappos

**Comment by lukehinds** [comment]
Ah do you know what, I will take one for the team. Let's keep @SantiagoTorres, I will drop off and then we can vote on the pool who have nominated (trishank, carlos joshua)

Just gave me credit as a past key holder on the readme.

**Comment by dlorenc** [comment]
OK - to summarize, the existing key holders will choose the next one out of a pool of self nominees. Luke has graciously volunteered to step down, thanks @lukehinds for your time on the rotation!

Let's do a "call for nominees" tomorrow in the community meeting to get our full list, then the keyholders can choose next week.

**Comment by nsmith5** [comment]
👋🏻 Hey folks I'd like to nominate myself. I've been meaning to learn more about the TUF root and I think this would help me do that. I'm active in the community and I've got a couple hardware keys I can use for this :) Either way, I'm looking forward to watching the rotation to learn how it all works in practice

**Comment by Foxboron** [comment]
Yo,
I'd like to nominate myself. I'm sadly not super active in the community because my FOSS engagement is mostly bound to my spare time. I'm from Norway and have access to several hardware tokens for securing the keys.

**Comment by lukehinds** [comment]
I would like to nominate Lily Sturmann  / @lkatalin 

She has done a lot of work over the past few months to get the sharding API and is someone I know is quite passionate about community transparency / open source.

**Comment by asraa** [comment]
This is done now! We will re-open another one for the next root-signing rotation, and move over nominations
