### ISSUE TITLE
Create staging environments

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#121]
We need a staging environment for two purposes:
1. Testing the TUF remote before it's used by Cosign. This is like a "pre-prod" environment, where the keys and targets are the same as production.
2. Creating TUF metadata for the Sigstore staging environment, which will have a different set of targets. We should use a different set of target signing keys.

Let's create a GCS remote for each case.

For (1), we can configure the GCS sync to first push to the remote, and delay the GCS sync to the production remote by a day (I think we should still automate this, I'd prefer that we don't need to give explicit approval for each GCS sync), which will give us time to validate risky changes. 

For (2), I know that we already have a TUF delegation set up for staging. Do we want to use this? Or do we want an entirely separate TUF root?

**Comment by Hayden-IO** [comment]
cc @asraa @dlorenc

**Comment by asraa** [comment]
We also definitely should turn on object versioning on the GCS bucket. I can't tell what made the root corrupt exactly (why snapshot.json was a mismatched size. I could speculate that different versions got on there, but I don't have visibility now).

This might mean creating a new GCS bucket.

> Or do we want an entirely separate TUF root?

I think we should use an entirely separate root to mimic it as close as possible. Parsing/using delegations would be another level of possible failures between staging and prod.

**Comment by Hayden-IO** [comment]
Object versioning can be enabled for existing buckets - https://cloud.google.com/storage/docs/using-object-versioning#set

Worth noting that cost might be something we have to consider long-term, so we could also set the "lifecycle rules" as per the documentation

**Comment by Hayden-IO** [comment]
Staging remote has been created with the Fulcio root and intermediate, Rekor pubkey, and CT log pubkey. The bucket is called `tuf-root-staging`. Assigning the bug to @asraa for creation of a preprod environment.

**Comment by Hayden-IO** [comment]
This issue will now be focused on the creation of the preprod environment.
