### ISSUE TITLE
Define GitHub variables

### ISSUE THREAD

**Issue by jku** [sigstore/root-signing#1261]
As part of #1247 I'd like to define a GH secret. 

* Secret TUF_ON_CI_TOKEN: this should be a sigstore-bot token with following permissions for sigstore/root-signing:
   * `Actions: write` to dispatch other workflows when needed
   * `Contents: write` to create online signing commits, and to create targets metadata change commits in signing events
   * `Issues: write` to create issues for workflow failures
   * `Pull requests: write` to create and modify signing event pull requests

There may already be a token but I'd like a new one to get the right name and to double check the permissions (they may not match exactly what the legacy systems needs).

---

Originally I was planning to also set two variables but that would only make sense if sigstore/github-sync would support them -- I will instead include them in the workflow in #1256

**Comment by jku** [comment]
Instead of the variables, we could just embed them directly in online-sign workflow if that's preferred (when I built this variable design I assumed they would be set by configuration-as-code...) in #1256

In fact I think I will do that: currently the variable would not be visible to project members in general and that feels wrong.

**Comment by jku** [comment]
for reference there is also an issue for using a GitHub App instead of a plain token https://github.com/sigstore/root-signing-staging/issues/98 -- I plan to test that in staging but that's not done yet

**Comment by Hayden-IO** [comment]
@bobcallaway Do you have access to sigstore-bot and can do this? (Also, how do we get access to sigstore-bot?)

**Comment by bobcallaway** [comment]
> @bobcallaway Do you have access to sigstore-bot and can do this? (Also, how do we get access to sigstore-bot?)

yes

**Comment by jku** [comment]
Thanks, this should now be sorted. We will see when the smoke clears after #1323
