### ISSUE TITLE
Replace online signer key for `registry.npmjs.org`

### ISSUE THREAD

**Issue by kommendorkapten** [sigstore/root-signing#1330]
As part of switching to tuf-on-ci, we are also updating the signer key for the npm delegation.

This will be a two step process:

1. Run `tuf-on-ci-delegate` to configure the new (online) key to use as part of the #1323 
2. Sign the updated delegation metadata with the new key

Note that as the signing will happen in another npm managed private repository, the signing step won't be visible in this repo. Only the commit which contains the signature.

**Comment by Hayden-IO** [comment]
Closing as this is complete, correct @kommendorkapten?

**Comment by kommendorkapten** [comment]
Yes, you are correct @haydentherapper, thanks.
