### ISSUE TITLE
decision on VERIFIER role

### ISSUE THREAD

**Issue by jku** [sigstore/root-signing#1362]
See https://github.com/sigstore/root-signing/blob/main/VERIFIER.md

I'm trying to establish how important the process described here is
* I don't remember seeing this verification being done visibly before  -- but maybe it was?
* In my opinion the hardware key authenticity part is not critical
  * tuf-on-ci already makes it impossible to "accidentally" use a non-hw key
  * if keyholder is malicious enough to secretly use a non-hw key (by modifying the signing software), I think we have far bigger problems and concentrating on the key being in a yubikey is not useful
* I am not sure how relevant the ceremony verification parts are now -- should we salvage something or no?

Comments @kommendorkapten or @haydentherapper ?

**Comment by jku** [comment]
see also #518

**Comment by kommendorkapten** [comment]
I think this is only relevant during the initial step for a new key holder, i.e when a key is added to `root.json`. Once it's there, it would be almost impossible to fake it, as the public key is kept in the signed metadata.

**Comment by jku** [comment]
> I think this is only relevant during the initial step for a new key holder

Can you be a bit more specific, do you consider the hardware key authenticity check relevant or some other part of the script?

If it's the hw authenticity check, do you think my arguments against it are reasonable?

**Comment by kommendorkapten** [comment]
> Can you be a bit more specific, do you consider the hardware key authenticity check 

Yeah, so when a _new_ key-holder is introduced, say a planned rotation, at that time, I think it's relevant to verify the authenticity of they public key added to `root.json`, by getting a device attestation from the Yubikey and making sure that the public key can be verified up to Yubico's CA. 

Once that is verified (and the proof recorded, e.g. as a comment in a PR), it's not as useful anymore, as the public key is now in the signed `root.json`, and so, the key can not be changed to a new one that is not belonging to a HSM.

**Comment by jku** [comment]
I have to admit I don't quite understand what we are protecting against here
* If the issue is malicious keyholder, the key location seems  irrelevant
* if the issue is trusted keyholder being somehow tricked into using a tampered yubikey, then
   * this seems like quite an involved attack -- maybe we should be sending the keyholders specific HW keys instead if this is really a significant issue 
   * could we just add a step to keyholder documentation  that directs them to https://www.yubico.com/genuine/ before accepting an invite?

Or maybe I'm missing some advantage?

For context, I'm trying to understand if I can remove the code, scripts and documentation related to this VERIFIER role in some way

**Comment by kommendorkapten** [comment]
> if the issue is trusted keyholder being somehow tricked into using a tampered yubikey, could we just add a step to keyholder documentation that directs them to https://www.yubico.com/genuine/ before accepting an invite?

As this is an open source project, I think transparency is important. How can I as a community member trust that they key is a legitimately Yubikey? Just having the key-holder verify it is not enough IMHO. Trust but verify.

Cryptographic evidence that all keys used are authentic Yubikeys removes any such questions. As this is the trust anchor for Sigstore's trust root, I think we should be as transparent as possible about the security posture we are using.

**Comment by jku** [comment]
If this is critical then it should be a part of the signing tools or at least the signing process, not some optional verifier role, right?

And the verification should actually check the keys used in the metadata, not what happens to be in a separate keys/ directory. I've not reviewed all of the code yet but so far I've not seen anything that verifies that the signing keys have a valid certificate in keys/. Is that actually done  somewhere?

**Comment by kommendorkapten** [comment]
The tooling today only prints the key id (by recomputing it over the public key), and verifies the certificate chain. So the complete verification does not appear to be automated.

Yes agreed, having device attestation verification built into the signing tool/process is preferable IMO. (This is how we are doing it at GitHub, each signature over root and targets are always verified against the public key coming from the device attestation, which is verified against Yubico's root CA.)

**Comment by kommendorkapten** [comment]
Going back to the question on what to do with the VERIFIER role, I think much of the role is due with the switch to TUF-on-CI, and the current tooling to compute the key id is not updated to work with the metadata format used (it does not take into account the `x-tuf-on-ci-` attributes. 

Removing them seems reasonable, and possibly replacing with a simple shell script that verifies the public key via openssl only. 

As an example, this public key https://github.com/sigstore/root-signing/blob/main/metadata/root_history/10.root.json#L68 corresponds to this key https://github.com/sigstore/root-signing/blob/main/repository/keys/15938791/15938791_pubkey.pem

**Comment by Hayden-IO** [comment]
For the verification of signed metadata, I don't think this role is necessary anymore as we have comprehensive automated testing.

As for verifying attestations on the Yubikey, your suggestion of "could we just add a step to keyholder documentation that directs them to https://www.yubico.com/genuine/ before accepting an invite?" seems sufficient to me. We should encourage keyholders to verify their Yubikeys, but I don't think we need to maintain our own scripts to do that if Yubikey provides such a utility. Maybe we can see if Yubikey has an open source utility rather than a website, to Fredrik's point about transparency?

**Comment by kommendorkapten** [comment]
> Maybe we can see if Yubikey has an open source utility rather than a website

There is a cli tool, you may be able to get the device attestations from that, so we don't need to maintain a tool just for that use-case.

**Comment by kommendorkapten** [comment]
There is a tool `ykman` https://developers.yubico.com/yubikey-manager/

some useful commands:

```
ykman piv keys attest 9c -
```

and 

```
ykman piv keys export 9c -
```

I can look more into this tomorrow, and see if there is simple way to verify using this.

**Comment by jku** [comment]
Okay, I think I'll do this:
* remove VERIFIER as a specific role and the related tools
* file a new issue about integrating "key authenticity check" into signing events, either as tuf-on-ci feature, a separate root-signing workflow or a just command that signers can run

**Comment by kommendorkapten** [comment]
Sounds good!
