### ISSUE TITLE
Documentation: Enhance linux instructions

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#137]
**Description**

I hit an error earlier: 
```
error: connecting to pscs: the Smart card resource manager is not running
```

We should add some docs for keyholders who hit this error to start and enable the pcsd daemon if they hit this issue
```
$ systemctl start pcscd.service
$ systemctl enable pcscd.service
```

**Comment by Hayden-IO** [comment]
Also worth checking what distros aren’t shipped with systemctl. init.d is another option.
