### ISSUE TITLE
Cannot reproduce `keyid` hash

### ISSUE THREAD

**Issue by lsd-cat** [sigstore/root-signing#1387]
I am trying to write a custom TUF client as an exercise to understand how it works.

I am testing it against `10.root.json`. Let's take for example key `22f4caec6d8e6f9555af66b3d4c3cb06a3bb23fdc7e39c916c61f462e6f52b06`.

```
"22f4caec6d8e6f9555af66b3d4c3cb06a3bb23fdc7e39c916c61f462e6f52b06": {
    "keyid_hash_algorithms": [
     "sha256",
     "sha512"
    ],
    "keytype": "ecdsa",
    "keyval": {
     "public": "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzBzVOmHCPojMVLSI364WiiV8NPrD\n6IgRxVliskz/v+y3JER5mcVGcONliDcWMC5J2lfHmjPNPhb4H7xm8LzfSA==\n-----END PUBLIC KEY-----\n"
    },
    "scheme": "ecdsa-sha2-nistp256",
    "x-tuf-on-ci-keyowner": "@santiagotorres"
}
```

I have attempted hashing:

```
{"keyid_hash_algorithms":["sha256","sha512"],"keytype":"ecdsa","keyval":{"public":"-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzBzVOmHCPojMVLSI364WiiV8NPrD\n6IgRxVliskz/v+y3JER5mcVGcONliDcWMC5J2lfHmjPNPhb4H7xm8LzfSA==\n-----END PUBLIC KEY-----\n"},"scheme":"ecdsa-sha2-nistp256","x-tuf-on-ci-keyowner":"@santiagotorres"}
```

```
{"keytype":"ecdsa","keyval":{"public":"-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzBzVOmHCPojMVLSI364WiiV8NPrD\n6IgRxVliskz/v+y3JER5mcVGcONliDcWMC5J2lfHmjPNPhb4H7xm8LzfSA==\n-----END PUBLIC KEY-----\n"},"scheme":"ecdsa-sha2-nistp256"}
```

```
{"keytype":"ecdsa","keyval":{"public":"-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzBzVOmHCPojMVLSI364WiiV8NPrD
6IgRxVliskz/v+y3JER5mcVGcONliDcWMC5J2lfHmjPNPhb4H7xm8LzfSA==
-----END PUBLIC KEY-----
"},"scheme":"ecdsa-sha2-nistp256"}
```

None of them, if hashed using SHA256, return `22f4caec6d8e6f9555af66b3d4c3cb06a3bb23fdc7e39c916c61f462e6f52b06` to me.

**Comment by lsd-cat** [comment]
Solved, one has to canonicalize all the fields inside "key" (is that TUF spec conform?) and the canonicalize function has to convert \n to actual newlines.

**Comment by jku** [comment]
> Solved, one has to canonicalize all the fields inside "key" (is that TUF spec conform?) and the canonicalize function has to convert \n to actual newlines.

I believe it is correct -- the spec is not very verbose about this but in general canonicalization must happen over all the fields (since new versions of the spec could add new optional fields; and old and new clients should be able canonicalize to the same value)... 

That said, in my opinion keyid calculation is dumb and should be removed from the spec (it's complicated and has no real security purpose) . I don't think a client is loses anything by not calculating the keyid: e.g. python-tuf does not care about it. You should be fine if you just consider keyid an identifier that's unique to that specific piece of metadata

**Comment by lsd-cat** [comment]
> That said, in my opinion keyid calculation is dumb and should be removed from the spec (it's complicated and has no real security purpose) . I don't think a client is loses anything by not calculating the keyid: e.g. python-tuf does not care about it. You should be fine if you just consider keyid an identifier that's unique to that specific piece of metadata

So that is why I could not find reference code for that in python-tuf!

How does it matches signers with signatures then?

**Comment by jku** [comment]
> How does it matches signers with signatures then?

Keyids are still identifiers: You can use the keyids found in roles and signatures to lookup the public key. The calculation is not required for any of that. Does this answer the question?

As far as I can tell the calculation was added as a "security mechanism" to prevent using the same public key twice but there are problems with that:
* first of all it's not relevant: if an attacker has the ability to add a key to a role multiple times, they also have the ability to add two separate keys to the role
* It also does not work: a single private key can have multiple TUF public key representations (meaning that there are multiple TUF keyids that look like separate keys that could be correct for any given private key)

**Comment by lsd-cat** [comment]
Thank you, this was very explicative!
