### ISSUE TITLE
Tagging "releases": Capture state at each root-signing event

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#141]
**Description**

This would be helpful to tag so that we can easily fetch the state of the repo initialization scripts for each root signing event.

I am testing a v3 change and realized it is probably easiest for me to "init" v1 w/ the v1 scripts, and so on.

**Comment by jku** [comment]
I've been thinking about tagging signing events (or maybe next published repository states) as well but I believe the specific need here is no longer relevant, closing.
