### ISSUE TITLE
Automate notification of new root to keyholders

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#149]
**Description**

And re-signing on any config changes.

Notify keyholders after the action runs.

**Comment by asraa** [comment]
Done in https://github.com/sigstore/root-signing/commit/fbd45af5663f4518c8ba9564e91ba688a21ae2ce

Will need to figure out how to notify keyholders. Changing title.

**Comment by jku** [comment]
I believe this is handled by signing events now naming the signers who need to sign (whether people read github notifications may be another matter though)
