### ISSUE TITLE
Size mismatches on the last root

### ISSUE THREAD

**Issue by dlorenc** [sigstore/root-signing#166]
I rolled back in #165, this was introduced in #163.

cc @haydentherapper @asraa

**Comment by asraa** [comment]
Investigating what's going on... the post-submit run verifying the published repo in this repository succeeded, and shows the corrupt version 24 update
https://github.com/sigstore/root-signing/runs/6033149661?check_suite_focus=true

Then the postsubmit on the revert (before sync runs) also shows the remote update successful to version 24s
https://github.com/sigstore/root-signing/runs/6033437058?check_suite_focus=true

Why CI mismatches cosign is troubling. I can add a cosign client test on these repositories in CI, but I don't know why there's a mismatch between the go-tuf client and cosign's tuf client

**Comment by dlorenc** [comment]
Here's the exact error:

```shell
Error: signing [gcr.io/rekor-testing/distroless]: getting signer: getting key from Fulcio: verifying SCT: updating local metadata and targets: updating tuf metadata: tuf: unexpected file size: snapshot.json (expected 1655 bytes, got 1659 bytes)
```

**Comment by dlorenc** [comment]
OK, I did a bit of debugging. The problem appears to be some sort of eventual consistency in the GCS API. When cosign fetches the contents over the http API, we're receiving the old version of the object. I verified this with curl. When you fetch over the GCS api, we get the new, valid version:

https://gist.github.com/dlorenc/f3861bf76d13f09fd942ddefac79f86b

**Comment by dlorenc** [comment]
I'm guessing it's related to this: https://cloud.google.com/storage/docs/caching

The default cache-control time is one hour. We should drop that on all these objects.

< cache-control: public, max-age=3600
< age: 3125

**Comment by dlorenc** [comment]
Working now!
