### ISSUE TITLE
Race condition when publishing new TUF metadata to GCS

### ISSUE THREAD

**Issue by znewman01** [sigstore/root-signing#171]
From [actions workflow](https://github.com/sigstore/root-signing/actions/runs/2179900395):

```
Run gcloud alpha --quiet storage cp --cache-control=no-store -r repository/repository/* gs://sigstore-tuf-root/
Copying file://repository/repository/1.root.json to gs://sigstore-tuf-root/1.root.json
Copying file://repository/repository/2.root.json to gs://sigstore-tuf-root/2.root.json
  
Copying file://repository/repository/rekor.json to gs://sigstore-tuf-root/rekor.json
Copying file://repository/repository/root.json to gs://sigstore-tuf-root/root.json
Copying file://repository/repository/snapshot.json to gs://sigstore-tuf-root/snapshot.json
Copying file://repository/repository/staging.json to gs://sigstore-tuf-root/staging.json
Copying file://repository/repository/targets/fulcio.crt.pem to gs://sigstore-tuf-root/targets/fulcio.crt.pem
Copying file://repository/repository/targets/ctfe.pub to gs://sigstore-tuf-root/targets/ctfe.pub
Copying file://repository/repository/targets/artifact.pub to gs://sigstore-tuf-root/targets/artifact.pub
Copying file://repository/repository/targets/rekor.pub to gs://sigstore-tuf-root/targets/rekor.pub
Copying file://repository/repository/targets/rekor.0.pub to gs://sigstore-tuf-root/targets/rekor.0.pub
Copying file://repository/repository/targets/fulcio_v1.crt.pem to gs://sigstore-tuf-root/targets/fulcio_v1.crt.pem
Copying file://repository/repository/targets.json to gs://sigstore-tuf-root/targets.json
Copying file://repository/repository/timestamp.json to gs://sigstore-tuf-root/timestamp.json
```

GCS has consistency [*within* objects, but not *across* objects](https://cloud.google.com/storage/docs/consistency). That is, if a client attempts to download the TUF metadata after `snapshot` is updated but before `timestamp.json` is finished updating, they might get a mismatch.

Possible solutions:

1. Stick the whole TUF repo into a tarfile or something similar to take advantage of within-object atomicity.
2. Use something like the "stick files in a directory named after the current timestamp, and have a symlink/pointer to the latest directory" trick
3. Turn on TUF consistent snapshots, and do (1) but only for the TUF metadata

CC @asraa

**Comment by Hayden-IO** [comment]
Would enabling consistent snapshots (which we are doing for the new root) along with copying in a specific order be sufficient? From the GCS docs, it notes that when we receive a success response, the object is available. If we write in a specific order, starting with the targets, then uploading targets metadata, snapshot metadata, the time stamp, then root (the reverse order that TUF reads metadata), would this work?

**Comment by znewman01** [comment]
I don’t believe so. If we do timestamp first, a client who grabs it in the middle has the new hash of snapshot.json but the old snapshot. If we do snapshot first the client will have the old hash of snapshot.json from the old timestamp.json with the new snapshot.json

**Comment by Hayden-IO** [comment]
I'm proposing we do snapshot before timestamp. For the normal TUF update flow, a client shouldn't request the new snapshot until the new timestamp has been uploaded, so even though they'll be a brief period where there's a mismatch in the remote, I think this should be fine.

**Comment by znewman01** [comment]
I'm still worried about the following sequence of events:

1. Repo uploads new `snapshot.json`
2. Client fetches old `timestamp.json`, validates signatures etc. ([section 5.4](https://theupdateframework.github.io/specification/latest/#update-timestamp))
3. Client fetches new `snapshot.json`, then fails when validating its hash ([section 5.5.2](https://theupdateframework.github.io/specification/latest/#update-snapshot))
4. Repo uploads new `timestamp.json`

Especially because each upload to GCS waits for the object to be persisted before finishing, GCS uploads might take much longer than it takes for the client to do (2) and (3).

This is a *pretty* unlikely scenario. But I'm curious if there's any prior art; I'll ask in the TUF slack.

**Comment by Hayden-IO** [comment]
Snapshots themselves are [versioned](https://theupdateframework.github.io/specification/latest/#update-snapshot), so in this case, when the client fetches the old timestamp, it would request the older snapshot, due to the older version number in the timestamp.

It would be nice if there was GCS support for uploading a set of files and only making them available once all have been uploaded.

**Comment by znewman01** [comment]
Whoops, I read the consistent snapshots part of the spec like 3 times yesterday and somehow missed that it applies to metadata files too…

It seems like the important thing is to push the new timestamp.json *last*, and the order otherwise doesn’t matter. Except now there’s a problem with pushing a new root.json that updates the timestamp role I think—-clients keep grabbing root.json versions until they can’t, and the timestamp file isn’t versioned so either order could cause problems

**Comment by asraa** [comment]
> . Except now there’s a problem with pushing a new root.json that updates the timestamp role I think—-clients keep grabbing root.json versions until they can’t, and the timestamp file isn’t versioned so either order could cause problems

I think you're right here that there's a root/timestamp race condition still possible. It's starting to seem appealing to do distribute as a tar-file, but then the major downside I see here is that you can't lazily download target files.

OTOH the frequency of root updates is very small... I don't like fixing this client-side because not every client should be responsible for handling this, but should we have a back-up root, and/or retries?

**Comment by Hayden-IO** [comment]
Yea, as the size of the repository grows, we will need to support per file downloads. 

Good point about the race between root and timestamp. For now we may just have to rely on the fact that the root is rarely updated.

Fetch the root, fetch timestamp, fetch root again?

**Comment by znewman01** [comment]
> It's starting to seem appealing to do distribute as a tar-file, but then the major downside I see here is that you can't lazily download target files.

Well, you could do a `.tar` of just the root files and `timestamp.json` :) But that feels really gross/hacky.

> OTOH the frequency of root updates is very small

Yeah, I don't think this is a huge priority, it's mostly theoretical.

> I don't like fixing this client-side because not every client should be responsible for handling this

Well, if we do it inside of TUF client libraries that feels a little bit more reasonable.

> but should we have a back-up root, and/or retries?

Yeah, I think retries would probably be nice and handle this often enough that we can ignore the issue. That's what I'm leaning towards right now.

**Comment by trishankatdatadog** [comment]
Hrm, sounds like we really should support writing and reading consistent snapshots. I've seen versions of this problem with S3 before. Is anyone up for sending a PR? It shouldn't be that hard...

**Comment by Hayden-IO** [comment]
To clarify, are consistent snapshots not implemented in go-tuf?

**Comment by asraa** [comment]
Maybe you mean here? FWIW we're slating that for the next root

**Comment by trishankatdatadog** [comment]
I have't looked into whether consistent snapshots are supported in go-tuf 🤔

**Comment by asraa** [comment]
They are!

**Comment by trishankatdatadog** [comment]
> They are!

Awesome possum: so we just need to turn it on

**Comment by znewman01** [comment]
I think we can close this out, since we're doing consistent snapshots and there's another issue to address this upstream: https://github.com/theupdateframework/specification/issues/223
