### ISSUE TITLE
conformance: Add python/rust TUF client presubmits to published repository

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#242]
**Description**

**Comment by asraa** [comment]
@SantiagoTorres This would be a great addition! I'm thinking a github workflow like `tuf-client-test.yml`

Something similar to https://github.com/sigstore/root-signing/blob/main/.github/workflows/cosign-test.yml

but instead of cosign, python-tuf or rust-tuf, and even go-tuf for redundancy

**Comment by SantiagoTorres** [comment]
Happy to take a look!

Just to make sure I understand, the idea would be to repeat that workflow using the other client tools and then add a consensus check to make sure we are cross-impl compatible?

**Comment by asraa** [comment]
> workflow using the other client tools and then add a consensus check to make sure we are cross-impl compatible?

Yep! That's right. I want to make sure we catch regressions that might make break Python/Rust TUF clients (so that we can also start integrating into sigstore-python/rs)

**Comment by SantiagoTorres** [comment]
Got it, let me take a look then...

**Comment by asraa** [comment]
Rust has been added. python-tuf remains. moving to v5 because it pends python compatibility.
