### ISSUE TITLE
Syncing from repository should overwrite remote

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#243]
**Description**

As found in the v3 root signing ceremony, we only copy files - This leaves stale files around. We should consider something like `rsync` or `mv`.

**Comment by Hayden-IO** [comment]
`gsutil rsync` exists, but there is no support for `rsync` with `gcloud alpha storage` yet

**Comment by Hayden-IO** [comment]
Will implement without `rsync`:
* `cp` all files from `source` to `dst`
* Fetch all files in `dst`
* Find all files in `dst` that are not in `source`
* Delete all those files

**Comment by asraa** [comment]
Completed in #247
