### ISSUE TITLE
credentials_file_path is deprecated for OIDC auth to GCP

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#246]
**Description**

[credentials_file_path](https://github.com/google-github-actions/setup-gcloud#authentication-inputs) is deprecated - We should update the sync scripts.

**Comment by asraa** [comment]
This is for the `setup-gcloud` action, not for `auth`.

https://github.com/google-github-actions/auth#other-inputs

I'm confused, maybe it used to be an option for `setup-gcloud`?

**Comment by Hayden-IO** [comment]
I assume so - The AI might just be to wait until `auth` has a different solution

**Comment by asraa** [comment]
I think the solution here is to use the `auth` job followed by `setup-gcloud`, without creating a `credentials_file_path`.

like this example https://github.com/google-github-actions/setup-gcloud#workload-identity-federation-preferred

**Comment by asraa** [comment]
Note that this option was not deprecated for `auth`: it was only deprecated for `setup-gcloud`, which we don't use!

**Comment by asraa** [comment]
I guess we do use it in `sync`, but without that option. But either way, I'll put out a PR to cleanup our auth.

**Comment by asraa** [comment]
@haydentherapper I think this is closed. I was looking at fixing this just now, but we don't use `credentials_file_path` for `setup-gloud`. We only use it for `auth`, where it is default true and is required for authenticating with gcloud.

https://github.com/google-github-actions/auth#other-inputs

It is also automatically removed at the end of the job

> The file is automatically removed at the end of the job via a post action.

so I think the concern that it could get leaked should be OK so long as we trust gcloud.
