### ISSUE TITLE
Add prober to exercise `cosign initialize`

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#263]
**Description**

The current prober only tests the workflow without a local cache.

**Comment by asraa** [comment]
I believe this is done. The prober in public-good-instance runs initialize, as well as the ones in this repo.

**Comment by Hayden-IO** [comment]
@asraa, it looks like the prober only runs initialize for [staging](https://github.com/sigstore/public-good-instance/blob/21a185a3716a9652b476325d77ead4ce9fd8fdfa/.github/workflows/reusable-prober.yml#L164). However, now with the work that you've done, the two flows are almost identical, correct?

**Comment by asraa** [comment]
> @asraa, it looks like the prober only runs initialize for [staging](https://github.com/sigstore/public-good-instance/blob/21a185a3716a9652b476325d77ead4ce9fd8fdfa/.github/workflows/reusable-prober.yml#L164)

All changes run through staging, right now there's no job that has access to push directly to prod. I assume that's why that prober references staging.

> However, now with the work that you've done, the two flows are almost identical, correct?

Yeah, I'm not sure what other flow we can test now.
