### ISSUE TITLE
Fix small bug in step 5 script around copying the repository

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#269]
**Description**

**Version**

The guard ([ -f $REPO/repository/*.root.json ]) was not working

**Comment by asraa** [comment]
Seems like this code was in the `v3-staging` branch to clear out old files
https://github.com/sigstore/root-signing/blob/v3-staging/scripts/step-5.sh

and is not in main
https://github.com/sigstore/root-signing/blob/main/scripts/step-5.sh

Closing, but creating a new issue around helper scripts to help modularize the script code.

**Comment by asraa** [comment]
https://github.com/sigstore/root-signing/issues/275
