### ISSUE TITLE
Investigate: Root newline change in snapshot update #286

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#287]
**Description**

Investigate:
* The root cause of why newlines were removed from root/targets in the snapshot update from #286 
* Why GitHub Actions was not triggering validate

@joshuagl @dlorenc

**Comment by asraa** [comment]
This is actually causing me problems in the verifier. 
Before the newline was removed, the targets file had 3972 bytes. Old TUF clients (before commit https://github.com/theupdateframework/go-tuf/pull/247) cannot verify metadata with the newline:
```
asraa@asraa1:~/git/go-tuf$ ./tuf-client list -s /tmp/tuf.db http://localhost:8001
ERROR: tuf: unexpected file size: targets.json (expected 3971 bytes, got 3972 bytes)
```

The client at head CAN verify with either the newline present or removed.

----------------------------------

Now, however, when we initialize a new root, we are adding the newline BACK. This means old clients cannot verify the change.

I'm still trying to figure out where we're using an old version of the client. I don't know why we are hitting the error.

**Comment by Hayden-IO** [comment]
I don't think this should be relevant anymore and we haven't seen this issue in some time. Closing.
