### ISSUE TITLE
Enhancement: Store the current keys/ folder under the top-level repository/

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#288]
**Description**

Right now `repository/` just contains the published metadata. It would be nice to store the current keys, so that I don't have to cp from the previous repo ceremony directory when I chain init fromthe next. When I do that, I need to grab updated snapshot/timestamp from the published repository.

If I store keys/ in the published repo, then the previous repo always becomes `repository/` and I don't need to search a ceremony directory for the old key material.

When I make this change, I'll start the playbook for orchestrating key ceremonies. Since this is a weird detail of the ceremony & repository folder structure

WDYT?
@haydentherapper @dlorenc  
I'd like to make that change, I think it's benign and simplifies the management.

**Comment by Hayden-IO** [comment]
`repository/repository` is mirrored to GCS currently, and we don't need to mirror the keys too. One option which could increase clarity is having an `output/` directory, and under that, `keys/` and `repository/`. Do you think that would help?

**Comment by asraa** [comment]
Thanks! Yes, `repository/repository$f` files are mirrored, NOT `repository/keys`, so that wouldn't get mirrored, as far as I can tell.

https://github.com/sigstore/root-signing/actions/runs/2549597503/workflow#L46-L51

**Comment by asraa** [comment]
Completed
