### ISSUE TITLE
Remove all targets before adding targets for a new ceremony

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#322]
**Description**

**Version**

Old targets like rekor.0.pub were left around.

**Comment by asraa** [comment]
@cdris this is a pretty easy issue. 

Right now we add targets that are given in the config https://github.com/sigstore/root-signing/blob/1445a1cf9c0d74a02b5f1495b6964f3c94f10523/cmd/tuf/app/init.go#L205

But we don't remove any pre-existing ones

Unless there's a remove all, we need to get the current target map and then remove any ones that weren't adding in the config https://github.com/sigstore/root-signing/blob/1445a1cf9c0d74a02b5f1495b6964f3c94f10523/cmd/tuf/app/init.go#L139
