### ISSUE TITLE
feat: Add correctness testing presubmits for Sigstore TUF clients

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#345]
**Description**

https://github.com/sigstore/root-signing/pull/343#discussion_r948037846

This would 
* Add verification of retrieved metadata (rather than only testing successful updates) in each TUF client
* Add Sigstore client verification against staged roots on presubmit

**Comment by jku** [comment]
I believe we have an equivalent process now:
* during a signing event, the validity of each modified metadata is verified individually
* once preprod is populated (after online signing happens), we run 
  * a TUF client smoke test that verifies repository validity (and that the repository matches the git sources) 
  * sigstore client tests with half a dozen clients
* if preprod tests fail, prod does not get published

So there is no "staged" repository here: there are some issues that will only be found in preprod testing: the recovery may mean a revert of the signing event merge.

What I would like to still see is artifact tests in signing event: in other words sigstore client(s)  testing the modified trusted_root.json without using TUF... but I'll still close this one as I think it's mostly covered now. Please reopen if I got it wrong.
