### ISSUE TITLE
Create issue on GitHub Actions failure

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#352]
**Description**

We should have visibility into Actions failures. For example, if the snapshot/timestamp action failed to trigger, there is currently no visibility into this failure, and it would cause an outage for verifiers. Assuming this is supported by GHA, I propose filing an issue on failure and tagging the maintainers.

cc @asraa

**Comment by asraa** [comment]
Sure, I can add an if-failed github issue

**Comment by dlorenc** [comment]
As a backup we already have probers that run and verify the root isn't about to expire. , IIRC.

**Comment by asraa** [comment]
Yeah there are probers verifying metadata is valid for the next 3 days, though. IMO not the hugest priority: I also get email alerts on fail. it's pretty easy to do though since i have a script for doing this in other repos anyway
