### ISSUE TITLE
Process improvement: Create a docker container to bundle code & configs

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#362]
**Description**

Downside is that people would need docker installed, but it would greatly simplify environment issues and running the code.

@bobcallaway thank you for the suggestion!

This would be nice to tackle in v6-v7. If we can get configs done in v6, then v7 would be a nice reasonable target for that.

**Comment by jku** [comment]
Can you describe a little more which code this is about -- the repository machinery,  keyholder tools or some verification tools?

**Comment by Hayden-IO** [comment]
I think this was about bundling what was in cmd/ into a docker container rather than building a binary each time we needed to use it. I think all code will be cleaned up now, so this can be closed.
