### ISSUE TITLE
Include new CT log key in v5 targets

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#389]
**Description**

We need to rotate the CT log key because it was checked into public-good-instance. We will be created a new shard. If the v5 signing is going to happen before we shard, then we should create the new signing key in advance.

cc @vaikas

**Comment by vaikas** [comment]
Indeed. When is the v5 signing slated to happen?

**Comment by Hayden-IO** [comment]
@asraa for the date - testing is happening now-ish.

I think we can just frontload the generation of the new key material. It doesn't need to go into KMS or anything, so we don't need to figure out resource names yet.

**Comment by asraa** [comment]
> Indeed. When is the v5 signing slated to happen?

Slated for Tuesday, and the target only needs to committed to `targets/` sub-folder here and an addition or the entry in `configs/targets-metadata.yml`

Let me know!

**Comment by Hayden-IO** [comment]
@vaikas , if I create the secret now on my local machine, will that be fine? Or is it expected that the createctlog job will handle secret creation?

**Comment by vaikas** [comment]
I think that's fine with me if it's fine with others. I need to add support for CTLog re-using existing key as discussed here:
https://github.com/sigstore/public-good-instance/issues/524#issuecomment-1254332280

So, I'll need to add support for reading the Key from a secret anyways to support ☝️ . So, I guess as long as we have a way to get this into a secret on the cluster this should be fine. WDYT?

**Comment by Hayden-IO** [comment]
That sounds great. I assume to get it into a secret, we just need someone to manually add the secret to GCP Secrets and then have some way that it's loaded into the cluster.

**Comment by Hayden-IO** [comment]
If the key is in a secret and loaded into the cluster via a file, do you see any reason to encrypt the key? I don't think it adds anything, because the password would come from another secret, and in the event of a compromise, both secrets could be obtained.

**Comment by Hayden-IO** [comment]
Generated with:

```
openssl ecparam -name prime256v1 -genkey -noout -out privkey.pem
openssl ec -in privkey.pem -pubout -out pubkey.pem

# verify
openssl ec -in privkey.pem -noout -text
openssl pkey -pubin -in pubkey.pem -text -noout
```

**Comment by asraa** [comment]
@haydentherapper could you please update the README as well? (may add as a TODO comment or note that supported in v5)

**Comment by Hayden-IO** [comment]
on it!
