### ISSUE TITLE
Create staging and ceremony branches for root testing

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#453]
This is an idea in conjunction with @jku

**Description**

Currently, we perform all repository actions on the `main` branch. Ceremony directories are created and then merged to a top-level `repository/` folder. This makes it difficult to stage new types of configurations for new or staging/testing roots without affecting the "prod" level `main` branch configuration.

**Proposal**

In order to reach https://github.com/sigstore/root-signing/issues/416 for a staging test root (test a new configuration) and to separate out `ceremony` events from the main, we can do the following:

1. Create `ceremony/DATE` branches when performing new root-signing events.
    - [ ] Update `init_repository.yml` scripts to work off branches and create pull requests on new branches.
2. Create a `staging` branch where we replace keys with fake HSM keys (which I have support for), and we effectively have a mirrored repository there where we can run test operations on the roots.

**Benefits**
* Code and workflows no longer needs to be configured on different `$REPO`'s but instead different `branch` names. All repositories work off `repository/`.
* We can stage a test root with fake HSM keys on a `staging` branch that can use staged configs, before we merge those configs to the `main` branch to use for actual ceremonies.
 
**Open Questions**
How to keep the non-repository code (workflows, scripts, binaries) in sync across the branches? Or should the branches only contain configuration and repositories?

**Comment by asraa** [comment]
As to not interfere with the current flow of ceremony root-signing, I can try to create the `staging` branch first.

**Comment by jku** [comment]
it's also possible that the ceremony branch could be a single branch with a well-known name:
* it makes sense that there is only one ceremony at a time
* with branches all changes end up in the history of the main branch: there's no need to store specifically named branches (you could still create specific tags when merging to main to document things)
* tool usage would be simpler -- no need to specify the ceremony name when the name is well known

Anyway, no need to rush this sort of change if the current ceremony process works: let's take our time.

**Comment by joshuagl** [comment]
Using branches for ceremonies and merging into main (with tags) to keep a history of approved changes sounds like a really neat approach.

**Comment by asraa** [comment]
Updates: ceremony branch support is now complete.

I have yet to set up a `staging` branch - which we can test here: https://github.com/sigstore/root-signing/issues/416

The nice part is that it can use the same reusable workflows, just with a different branch name, so we'll get testing from that. Work needs to be done to (1) ensure that the keys are substituted for test HSM and (2) all other metadata is synced
