### ISSUE TITLE
Tracking issue for Timestamp Authority chain in TUF targets

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#466]
**Description**

Once sigstore/timestamp-authority is deployed, we'll need to include the cert chain in the targets.

**Comment by asraa** [comment]
Usage: TSA? I think that works.

**Comment by Hayden-IO** [comment]
That sounds good.

**Comment by asraa** [comment]
Brian just put out a root of trust spec, and I'd like to vreate the v6 milestone that includes this. @bdehamer @malancas do you have an ETA on when the TSA would be deployed? Is it worth reserving a key now in the root of trust for v6 (even if it's not deployed yet)?

**Comment by Hayden-IO** [comment]
Another question, will we leverage delegation for this?

**Comment by asraa** [comment]
> Another question, will we leverage delegation for this?

Part of it might depend on timeline, but I am not sure it completely falls the use-case for one, this is why:

* Do we want independent repo control of the key? As in, key revocations and rotations are managed independently of this repo? If so, what is the rationale? If it belongs to a public-good-instance and relevant to the public good network, then why not update it here centrally?
* Do we want to manage a delegation signing key and the auth required for that? (As in, who is the delegation party that is scope for TSA rotation?) I can somewhat see the case for this, but it's tricky to perform validation and rotation of the delegation signing key, so I would only want to do that if it's necessary. If it is lumped into npm delegation, I guess it's nice to re-use but I would caution that that seems to blur the role independence of npm and the TSA. 
* [implementation reason only] Since it's a somewhat critical feature, putting it in a delegation update flow would complicate adoption and possibly also break. I'd rather delegations be scoped to experimental or specific non-ecosystem-wide features.

If a delegation is a yes, it might take me more time to figure out, but it can always be possible. 
@jku @kommendorkapten

**Comment by Hayden-IO** [comment]
One motivation is that it's a different trust domain than the other keys. Does being in the top level mean "this key is owned by the sigstore organization?", or "this key is preferred by the sigstore organization?" I have assumed the former, but either way, we have not documented this I believe.

There at least needs to be some way to know that the key is owned by GH and not Sigstore in my opinion. Maybe it's sufficient to just have the URL, like with the `trusted_roots` proposal?

**Comment by kommendorkapten** [comment]
For the TSA hosted by GitHub, I think the driver for having it as a delegate or not is the client use-cases. 
If "mainstream" Sigstore clients are expected to use the certificate chain for the GH TSA, I think it should be a top level target. 
If we are only looking for an eco-system specific use-case (like npm registry signing keys) I think a delegate makes more sense.

**Comment by asraa** [comment]
This makes a lot of sense. If Sigstore clients are using the TSA as a top-level "resource" on the signing path, I'd expect it's just as critical in the general Sigstore verification flow.

+1 for staging it then in the TrustedRoot. I'll add this to v6 milestone!

**Comment by Hayden-IO** [comment]
I think Sigstore clients should use it for verifying artifacts, but the primary reason for its addition is NPM. It's kind of in the middle of the two - A verifier that Sigstore views as trustworthy, but not managed by Sigstore. I still think we need to differentiate this verifier from the other targets for this reason.

**Comment by asraa** [comment]
> A verifier that Sigstore views as trustworthy, but not managed by Sigstore.

The idea isn't about management, but about the client workflow. 

If ONLY npm clients are using this, then it makes sense for a delegation. But I expect all Sigstore clients / the broader Sigstore ecosystem to be using this TSA. Right?

**Comment by Hayden-IO** [comment]
To confirm, npm is recommending using Cosign and/or using the Sigstore TUF root for verification @kommendorkapten, correct? If so, yes, that makes sense.

**Comment by asraa** [comment]
> To confirm, npm is recommending using Cosign and/or using the Sigstore TUF root for verification @kommendorkapten, correct? If so, yes, that makes sense.

Yeah, I think general Sigstore clients should be able to verify npm provenance. Including the npm CLI tooling, slsa-verifier, and Sigstore clients that understand Sigstore bundles.

**Comment by kommendorkapten** [comment]
> > To confirm, npm is recommending using Cosign and/or using the Sigstore TUF root for verification @kommendorkapten, correct? If so, yes, that makes sense.

> Yeah, I think general Sigstore clients should be able to verify npm provenance. Including the npm CLI tooling, slsa-verifier, and Sigstore clients that understand Sigstore bundles.

Echoing what @asraa said. The npm provenance itself is not special, it will be two attestations (in-toto statements), one SLSA provenance and one custom predicate type. 

The attestations will each be embedded in a bundle. So any client that can verify an bundle, or extract the in-toto statement will be able to verify it as normal. For npm itself, of course the primary verifier will be the npm CLI.

One difference between the two attestations is that the SLSA provenance will be signed via ephemeral keys/Fulcio, and the publish attestation signed by a private key, by the registry. The registry's public key is what I will expect be delivered via a npm delegate in Sigstore's trust root. This would mean that any client that wishes to verify the publish attestation would need to know how to get the public key (via the delegate), I think in general only the npm CLI would have this knowledge. A use can of course get the public key and provide "manually" during verification.

Both attestations will be put on Rekor.

**Comment by asraa** [comment]
Removing this from `v6` tracking, and punting to the `npm` milestone.

**Comment by Hayden-IO** [comment]
TSA comes from trusted third parties.
