### ISSUE TITLE
Update verifier playbook with steps to test major changes manually

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#518]
**Description**

https://github.com/sigstore/root-signing/blob/main/VERIFIER.md

This would include initializing cosign from scratch, and initializing cosign from an existing root.

Inspired by the verification comments in https://github.com/sigstore/root-signing/pull/512

**Comment by jku** [comment]
So this is about testing artifact changes (like a new `trusted_root.json`) before signing them?
This makes sense:
* the test should definitely happen in the workflow -- failure should prevent merging the signing event even if signers sign
* but a validation tool for `trusted_root.json` would make sense for signers as well

**Comment by Hayden-IO** [comment]
Unfortunately I don’t remember the context on this, but given we are tracking verifying the trusted root in another issue, I’m good to close.
