### ISSUE TITLE
Trigger prod sync on 11/01 if pre-prod probers are stable

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#525]
**Description**

Current timestamp expires on 11/03: we just pushed the update to pre-prod today 10/31. To avoid root prober failures, we should push the update to prod after validate pre-prod probers are stable.

@haydentherapper

**Comment by Hayden-IO** [comment]
FYI oncall @priyawadhwa @patflynn

**Comment by asraa** [comment]
Done
