### ISSUE TITLE
Include active log ranges in custom metadata

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#533]
**Description**

Right now we have a binary Active/Expired for `status`. Let's introduce a custom metadata field like `not_before` and an optional `not_after` for extra validity.

This will allow clients to verify that the key was active during the integrated_time, which may help detect whether an expired key was used maliciously to fake a new entry.

Note: when performing offline verification, we still won't be able to detect whether an expired key was used to fake an entry during the expired log's active time, but the attack for that is a lot more complex (also requiring faking a cert valid during that expired time).

**Version**

**Comment by kommendorkapten** [comment]
I think may possibly close this and aim for https://github.com/sigstore/root-signing/issues/539 instead (publishing the trust bundle as a target, which then have structured field for such data).

**Comment by asraa** [comment]
Let's close this! Now totally superseded by the trust bundle.
