### ISSUE TITLE
cut releases of verify command

### ISSUE THREAD

**Issue by bobcallaway** [sigstore/root-signing#574]
**Description**

Currently, there are places where sigstore infrastructure is pinning to the `verify` utility at specific commits. Dependabot is not recommending upgrades because it can not safely determine whether or not a subsequent commit is appropriate or not. It would be ideal if root-signing created tagged releases, so that dependabot would properly notice changes and recommend that we use the latest `verify` utility.

**Comment by bobcallaway** [comment]
@asraa

**Comment by asraa** [comment]
I'll take a look! I might need to loop in some release help, but happy to cut some tags to mark state.

**Comment by Hayden-IO** [comment]
Check out the TSA repo, we have a really simple way of cutting releases by pushing a tag and building on GitHub actions.

**Comment by asraa** [comment]
Thanks! I'll tackle this today
