### ISSUE TITLE
Use `gitattributes` to control `git`'s `autocrlf` handling on ceremony outputs

### ISSUE THREAD

**Issue by woodruffw** [sigstore/root-signing#587]
**Description**

I just spent an hour debugging this on `sigstore-python`, so I figured I'd share here as well in case it ever bites someone trying to consume this repository on Windows 🙂 

A lot of Windows users have `core.autocrlf = true` set in their `git` configurations (and GitHub Actions does it automatically for checkouts as well). This is normally the right behavior (since it fixes line endings to match what Windows expects), but it *will* break any TUF metadata stored as JSON, since the file sizes on disk will no longer match their specified sizes in the root metadata. 

To fix it, this repo can add a `.gitattributes` file like this:

```gitattributes
ceremony/** binary
```

...which will tell `git` to treat everything under `ceremony/` as if its a binary file, meaning that `autocrlf` won't apply to it.

For context, here's the bug as it manifested in `sigstore-python`: https://github.com/sigstore/sigstore-python/pull/433

**Comment by asraa** [comment]
Oh wow, thank you so much for filing this report! I will definitely add this fix.

Ahhhhh so this is likely going to affect anyone who is pulling in these files into github repositories.

I vaguely remember hitting this at some point in this repository too. Or in cosign. And having to manually update the newline and then it never happened again for some reason.

Thank you!! I didn't know about this config.

**Comment by woodruffw** [comment]
No problem, happy to help! I too didn't know about it, until I spent an hour debugging it on high-latency Windows CI runners 🙃
