### ISSUE TITLE
[ci] Add branch protection to all branches (ceremony/* and test-ceremony/*)

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#635]
**Description**

Add branch protection on the new staging ceremony branches.

@haydentherapper could you look into copying our existing required checks to these two branch patterns (or all)?

**Comment by cpanato** [comment]
I can do that @asraa 

will open a PR soon

**Comment by asraa** [comment]
Thank you!! I really appreciate it! :)

**Comment by cpanato** [comment]
PR: https://github.com/sigstore/community/pull/232
