### ISSUE TITLE
[feature] Create a workflow for creating a PR that merges ceremony branch to main 

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#669]
**Description**

Once a publish to a branch is completed (see https://github.com/sigstore/root-signing/pull/666 for the test ceremony branch), we need a workflow that can be triggered that creates a PR against main.

It would also be nice for a workflow that, on merge of this PR, creates a tag on main automatically. See https://github.com/sigstore/root-signing/issues/141

**Comment by asraa** [comment]
@kommendorkapten I think this is the last critical orchestration item needed - I'll take care of it right now.

**Comment by kommendorkapten** [comment]
Awesome, thanks!

**Comment by jku** [comment]
closing, should not be relevant anymore
