### ISSUE TITLE
Update documentation and workflows for signing ceremonies

### ISSUE THREAD

**Issue by kommendorkapten** [sigstore/root-signing#689]
**Description**
The documentation states that the "snapshot and timestamp" workflow should also run the publish step: https://github.com/sigstore/root-signing/blob/main/playbooks/ORCHESTRATION.md#step-3-snapshotting-and-timestamping

Currently it does not, only the `stable-snapshot-timestamp` does that, the `staging-snapshot-timestamp` does not. It should accept a parameter to determine if the publish step should be run or not.

Currently when performing a signing ceremony, after the ceremony branch has been updated with snapshot and timestamp signatures, the `step-4.sh` has to be executed locally from the checked out branch.

**Version**
Current state as of root v6 signing.

**Comment by asraa** [comment]
Thank you! I think this was my mistake, for some reason I ommitted the publish step - there's no harm in running publish after, I think too many PRs to review is unncessary.
