### ISSUE TITLE
[v7] Schedule a test run and ceremony date

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#702]
**Description**

Message #sigstore-keyholders on Slack to determine a test run date where at least 3 keyholders can be present (and others can follow local test instructions) and a final ceremony date tentatively late March or first week of April.

**Comment by kommendorkapten** [comment]
I've added a desired end date for the v7 signing on the milestone last week: https://github.com/sigstore/root-signing/milestone/4
We would _really_ want the ceremony to happen on March 21st, and so the test ceremony next week 😬

**Comment by asraa** [comment]
> We would really want the ceremony to happen on March 21st, and so the test ceremony next week

Since the last one was pretty recently, we can ask the keyholders to test asynchronously - the most important part of the flow will be to test the delegation signing, which doesn't require any sigstore keyholders (but does require the npm one). As in, test initializing on a branch, create delegation stub/POP, verify it, merge it, and sign delegation PR. WDYT? 

We won't be able to test the merge to main, which we know has the DCO problem unless we can fix sooner, but we are aware of the automation problem and I can make sure to fix the snapshot/timestamp conflict.

**Comment by kommendorkapten** [comment]
Yea, I understand this is a tight schedule, I'm looking to if we can punt it a few weeks to get all things in order.

**Comment by asraa** [comment]
looks like we can schedule the prod one for April 4th, and signers can locally test signing the week before on the 28th.

@kommendorkapten the two of us can test the PR creations for delegations sometime before you go (week of 20th) since you'll have that set up?

**Comment by kommendorkapten** [comment]
Yes, that sounds good @asraa !

**Comment by asraa** [comment]
Closed - events are on the Sigstore Maintainer cal!
* Mar 21 - test delegation workflows
* Mar 28 - keyholders async testing locally
* Apr 4 - production signing
