### ISSUE TITLE
[v7] [docs] Update ORCHESTRATION.md documents with a delegation step

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#703]
**Description**

When adding a delegation, we will need to do the following, at least manually first, with an aim of updating to automation after.

The update will be that after running Step 2 (Initialize): https://github.com/sigstore/root-signing/blob/main/playbooks/ORCHESTRATION.md#step-2-initializing-a-root-and-targets but before `Hardware Key Signing`, we will need to add a step for updating the targets with an external delegation.

```
### Step 3: Adding external delegations

This step will add a delegated role to the top-level targets that is controlled by an external GitHub repository. Coordinate with the delegation keyholder to run the `add-delegation` (see https://github.com/sigstore/root-signing/pull/611) script or workflow that opens a PR in root-signing with a comment that contains a key proof of posession. The PR MUST begin with the title `feat/add-delegation for`. 

This will trigger the verify POP workflow that verifies the challenge (see https://github.com/sigstore/root-signing/pull/619/) and post a comment with the verification output. Run the `./scripts/dpop-verify.sh` script manually as well to review, and also ensure that `./scripts/verify.sh $PR` runs on the PR to validate the `targets.json` has a valid format. Merge the PR.
```

Technically, the next step can run simulatneously to  `Hardware Key Signing`.

```
### Step 4: Signing Metadata

Signing root & targets can occur simulataneously with signing delegation files without conflicting PRs, so alert top-level keyholders and delegation keyholders to create their signed metadata PRs.

Perform Hardware Key Signing for signing root/targets.

Coordinate with the delegation keyholder to run a targets creation and signing command on their delegation file to open a PR updating the signatures on their delegation metadata file.
```

cc @kommendorkapten

**Comment by asraa** [comment]
@kommendorkapten WDYT about this flow? (init -> add delegation PR -> sign root/targets and sign delegation PR)

We can technically run the sign root/targets at the same time as sign delegations, so let's actually suggest that for ease of all the keyholders.

**Comment by kommendorkapten** [comment]
Yes, I think it makes sense, great work!

I care prepare a PR to update the docs after I got the delegation workflow in and have successfully tested it.
