### ISSUE TITLE
[delegations] Create a reusable workflow that can create a delegations metadata file and sign

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#704]
**Description**

Consume this workflow in an external repository.

Ensure that this workflow can 
1. Checkout a configured repository & branch  (root-signing and the ceremony branch)
2. Create the metadata file (or update)
3. Sign with a key 
4. Create a PR with the updated the delegation file against the configured repository & branch

cc @kommendorkapten

**Comment by asraa** [comment]
Closed, because will be handled by the delegation

**Comment by jku** [comment]
this should be decently handled by `tuf-on-ci-delegate` (to create the delegation) and `theupdateframework/tuf-on-ci/actions/online-sign-targets` action for signing in delegated metadata in a workflow
