### ISSUE TITLE
[test] Generalize cosign-test.yml presubmit to cover all Sigstore clients

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#709]
**Description**

This would ensure that before pushing to pre-prod or prod, we detect if the END TO END flows of the sigstore clients (sigstore-python, sigstore-rs, sigstore-js) can successfully understand TUF metadata.

cc @di @jku

**Comment by jku** [comment]
I think this is now covered -- custom-test.yml currently handles cosign, go, js, python and java
