### ISSUE TITLE
Different nonce strategy when adding/updating a delegation key?

### ISSUE THREAD

**Issue by kommendorkapten** [sigstore/root-signing#729]
**Description**
Today when a delegation is added, we require a POP (Proof Of Possession) where the delegate key owner creates a signature over a combination of the `role name` and a `nonce`. The nonce is currently taken as the fork point from the `ceremony branch` and `main`, see [here](https://github.com/sigstore/root-signing/blob/e342408c0db1bc9b1702c3443f858aad6bb3420f/scripts/dpop-verify.sh#L55). 
This is quite convenient as we don't need to prepare any OOB data to use for signing and verification. 
This could pose a problem, if multiple delegations are to be added/modified in the same ceremony. From @haydentherapper ([link](https://github.com/sigstore/root-signing/pull/728#discussion_r1138889064)): 

> @haydentherapper: Any risk of nonce reuse for multiple delegations signed from the same fork point? Any reason this isn't a random value that we store somewhere?

> @kommendorkapten: This would be an issue only if we add multiple delegations at the same signing ceremony. We could add a step where the "ceremony orchestrator" adds a nonce in e.g. the repository/staged directory, with the name of the role, that could be used. I'll create a tracking issue for this, as I don't think it's a blocker now.
> 
> Also, I'm not sure if there is a risk in reusing the nonce as the challenge (role name) is also part of the POP, and the challenge is unique. But let's discuss this further in the issue.

Lets discuss if we should change how the nonce is generated/delivered or if the existing solution is sufficient.

**Comment by asraa** [comment]
Originally I thought about using the PR number - this would require a little change in tooling, where the PR would need to be created (or drafted first) and THEN the POP comment posted. 

We could do something like HASH(fork_point | PR) - @haydentherapper ?

**Comment by kommendorkapten** [comment]
> We could do something like HASH(fork_point | PR) 

Today we sign after a pre-auth encoding (DSSE like PAE):
`"key-pop-v1 len($role_name) $role_name len(nonce) $nonce"` (fork-point is the nonce) then we sign that string. So we are signing unique values, even if the nonce is reused.

First opening the PR could work too, I need to think more about how that would work. Or, the orchestrator just prepare a nonce like `repository/staged/$role_name` which is a binary file with random data.

**Comment by Hayden-IO** [comment]
The only issue would be reuse of nonce and role name then, yea? iRole name shouldn't be reusable since it should be unique, so I'm less concerned now. Including PR number also seems like a good approach!

**Comment by kommendorkapten** [comment]
Can we close this? As the likelihood of a collision is virtually zero. The POP is created over the role name (unique) and the git SHA from which the ceremony branch was created.
