### ISSUE TITLE
[docs] Update delegation documentation with code snippets when available

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#751]
**Description**

Right now, adding a delegation is done by triggering a PR - we should link in to some example documentation of an open sourced repository that runs code for managing this.

- [ ] Add a reference to code that creates the POP, to replace the bash scripted tuf binary scripts https://github.com/sigstore/root-signing/pull/728/files#r1140250194
- [ ] Add a reference or code snippet to a workflow or script that opens a PR against root-signing with the added delegation metadata to the targets and the signed delegation targets file
https://github.com/sigstore/root-signing/pull/728/files#r1140249150

**Comment by kommendorkapten** [comment]
As I already have the majority of this work done in another repository, I can work on this after easter, i,e ~mid April.

**Comment by asraa** [comment]
SG! No rush, just for tracking :)

**Comment by jku** [comment]
I think we can close this now: Adding a new delegation with `tuf-on-ci-delegate` is relatively simple.
