### ISSUE TITLE
trusted_root.json issue: common name is not the same for all certificates in the chain

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#757]
https://github.com/sigstore/root-signing/blob/main/targets/trusted_root.json#L41 - This assumes the common name is the same for both certificates in the chain. This is the root's CN, but the intermediate is "sigstore-intermediate".

Not sure how this will be used, but this should be configurable per-cert for a future iteration.

cc @bdehamer @kommendorkapten @asraa

**Comment by asraa** [comment]
Was the intent that you only care about the root name? The intermediate is sort of "hidden"/"implementation detai" of verification.

Yeah, the intent is that this is for the root CA https://github.com/sigstore/protobuf-specs/blob/c8a23a43dc1c685d336d112864ba237a15061c53/protos/sigstore_trustroot.proto#L46-L48

The cert chain just holds the intermediates, but the CA is a reference to the root CA

**Comment by Hayden-IO** [comment]
Closing because this seems to only be about the root

**Comment by kommendorkapten** [comment]
The intention in the trusted root is to surface the common name of the root for easier selection. We can clarify that in the protobuf comment if needed.
