### ISSUE TITLE
`trusted_root.json` in staging

### ISSUE THREAD

**Issue by tnytown** [sigstore/root-signing#758]
The staging TUF instance doesn't have a `trusted_root.json` target. `sigstore-python` does online tests with the staging instance, and it would be useful to have a bundled trusted root instance there.

**Comment by tnytown** [comment]
Oops, does #756 contain the changes for this?

**Comment by asraa** [comment]
Yep, this is a dupe of https://github.com/sigstore/root-signing/issues/755
