### ISSUE TITLE
trusted_root.json issue: Changing log ID format

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#759]
Talking with @bdehamer, the log IDs' key ID was generated as such: `echo -n "<base64 DER, aka the key without PEM headers>" | base64 -d | shasum -a 256 | cut -d ' ' -f 1 | xxd -r -p | base64`

This translates to the base64 encoded SHA256 digest of the raw bytes of the key. This is indeed what the protobuf docs say [here](https://github.com/sigstore/protobuf-specs/blob/c8a23a43dc1c685d336d112864ba237a15061c53/protos/sigstore_common.proto#L87-L90), but this is not the RFC6962 spec, which is the SHA256 digest of the PKIX encoded key, which is an ASN1 structure with both a key algorithm OID and key bytes ([rfc](https://www.rfc-editor.org/rfc/rfc5480#:~:text=SubjectPublicKeyInfo%20%20%3A%3A%3D%20%20SEQUENCE)).

We should regenerate the key IDs in this format, or choose to deviate from rfc6962. There's no requirement that we follow this spec, it's only helpful because Rekor is generating its log IDs following this format.

cc @asraa @kommendorkapten

**Comment by bdehamer** [comment]
> it's only helpful because Rekor is generating its log IDs following this format.

Is this true? 

The `logID` I see in the [Rekor response](https://rekor.sigstore.dev/api/v1/log/entries?logIndex=9430952) is `c0d23d6ad406973f9559f3ba2d1ca01f84147d8ffc5b8445c224f98b9591801d`. Translating this from hex to base64 yields the same value we're currently using in the [trusted_root.json](https://github.com/sigstore/root-signing/blob/main/targets/trusted_root.json#L15):

```console
$ echo "c0d23d6ad406973f9559f3ba2d1ca01f84147d8ffc5b8445c224f98b9591801d" | xxd -r -p | base64
wNI9atQGlz+VWfO6LRygH4QUfY/8W4RFwiT5i5WRgB0=
```

This appears to be just the digest of the raw bytes of the key:
```console
$ echo "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2G2Y+2tabdTV5BcGiBIx0a9fAFwrkBbmLSGtks4L3qX6yYY0zufBnhC8Ur/iy55GhWP/9A/bY2LhC30M9+RYtw==" | base64 -d | shasum -a 256 | cut -d ' ' -f1 | xxd -r -p | base64
wNI9atQGlz+VWfO6LRygH4QUfY/8W4RFwiT5i5WRgB0=
```

**Comment by bdehamer** [comment]
FWIW the Fulcio ctlog also appears to use the same scheme for calculating the log ID.

Here's the SCT from a recently issued cert:
```
CT Precertificate SCTs:
    Signed Certificate Timestamp:
        Version   : v1 (0x0)
        Log ID    : DD:3D:30:6A:C6:C7:11:32:63:19:1E:1C:99:67:37:02:
                    A2:4A:5E:B8:DE:3C:AD:FF:87:8A:72:80:2F:29:EE:8E
        Timestamp : Mar 23 17:41:31.260 2023 GMT
        Extensions: none
        Signature : ecdsa-with-SHA256
                    30:45:02:20:5E:E9:A8:F3:B9:63:4A:54:F0:74:21:F4:
                    40:AA:78:2C:DE:DB:5D:DF:A6:6C:2C:01:8E:72:62:14:
                    89:F2:A9:09:02:21:00:C1:DF:F3:C5:AA:85:6E:6E:EE:
                    71:E2:A3:86:87:68:2E:AA:64:A6:3D:C5:EE:D7:39:3E:
                    2C:2F:A6:D6:BC:1D:FB
```

Converting that log ID to base64:
```console
$ echo -n "DD3D306AC6C7113263191E1C99673702A24A5EB8DE3CADFF878A72802F29EE8E"  | xxd -r -p | base64
3T0wasbHETJjGR4cmWc3AqJKXrjePK3/h4pygC8p7o4=
```

Which matches the digest of the bytes of the key:
```console
$ echo -n "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEiPSlFi0CmFTfEjCUqF9HuCEcYXNKAaYalIJmBZ8yyezPjTqhxrKBpMnaocVtLJBI1eM3uXnQzQGAJdJ4gs9Fyw==" | base64 -d | shasum -a 256 | cut -d " " -f 1 | xxd -r -p | base64
3T0wasbHETJjGR4cmWc3AqJKXrjePK3/h4pygC8p7o4=
```

Which matches the value in the trusted_root.json:
https://github.com/sigstore/root-signing/blob/f036fabd0950fd312657a01158f6faee4931da80/targets/trusted_root.json#L86

So we may not be calculating these IDs according to the RFC, but we're at least calculating them consistently within the Sigstore ecosystem.

**Comment by bdehamer** [comment]
@haydentherapper it just occurred to me . . . I think this all just works by nature of the fact that our keys are ALREADY in the `SubjectPublicKeyInfo` format:

```console
$ echo -n "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEiPSlFi0CmFTfEjCUqF9HuCEcYXNKAaYalIJmBZ8yyezPjTqhxrKBpMnaocVtLJBI1eM3uXnQzQGAJdJ4gs9Fyw==" | base64 -d | openssl asn1parse -inform der -i
    0:d=0  hl=2 l=  89 cons: SEQUENCE
    2:d=1  hl=2 l=  19 cons:  SEQUENCE
    4:d=2  hl=2 l=   7 prim:   OBJECT            :id-ecPublicKey
   13:d=2  hl=2 l=   8 prim:   OBJECT            :prime256v1
   23:d=1  hl=2 l=  66 prim:  BIT STRING
```

**Comment by asraa** [comment]
Hmmm it sounds like we can close this @haydentherapper . The DER encoding seems like it's over the ASN.1 structure that's RFC compliant.

**Comment by kommendorkapten** [comment]
Agree that we can close this, then update https://github.com/sigstore/protobuf-specs/pull/73 to tighten the language in the comment, similar to RFC 6962.

**Comment by Hayden-IO** [comment]
@bdehamer Sorry for the delay, thanks for looking into this. You're right, PKIX encoding is the SubjectPublicKeyInfo, as noted in https://www.rfc-editor.org/rfc/rfc7468.html. This is fine for the ECDSA keys, which we encode as PKIX. RSA public keys can be PKIX encoded, but more commonly are PKCS#1 encoded, like what's in the [staging root for ctfe/test](https://lapo.it/asn1js/#MIICCgKCAgEA27A2MPQXm0I0v7_Ly5BIauDjRZF5Jor9vU-QheoE2UIIsZHcyYq3slHzSSHy2lLj1ZD2d91CtJ492ZXqnBmsr4TwZ9jQ05tW2mGIRI8u2DqN8LpuNYZGz_f9SZrjhQQmUttqWmtu3UoLfKz6NbNXUnoo-NhZFcFRLXJ8VporVhuiAmL7zqT53cXR3yQfFPCUDeGnRksnlhVIAJc3AHZZSHQJ8DEXMhh35TVv2nYhTI3rID7GwjXXw4ocz7RGDD37ky6p39Tl5NB71gT1eSqhZhGHEYHIPXraEBd5-3w9qIuLWlp5Ej_K6Mu4ELioXKCUimCbwy-Cs8UhHFlqcyg4AysOHJwIadXIa8LsY51jnVSGrGOEBZevopmQPNPtyfFY3dmXSS-6Z3RD2Gd6oDnNGJzpSyEk410Ag5uvNDfYzJLCWX9tU8lIxNwdFYmIwpd89HijyRyoGnoJ3entd63cvKfuuix5r-GHyKp1Xm1L5j5AWM6P-z0xigwkiXnt-adexAl1J9wdDxv_pUFEESRF4DG8DFGVtbdH6aR1A5_vD4krO4tC1QYUSeyL5Mvsw8WRqIFHcXtgybtxylljvNcGMV1KXQC8UFDmpGZVDSHx6v3e_BHMrZ7gjoCCfVMZ_cFcQi0W2AIHPYEMH_C95J2r4XbHMRdYXpovpOoT5Ca78gsCAwEAAQ).

I'd say the simplest way to proceed is updating the language in the comment, and I'll update the RSA key's encoding to be PKIX. ~Other option is to allow different encodings, but that seems unpleasant.~ See below, I prefer that.

**Comment by Hayden-IO** [comment]
Another option is to say it's the digest of what's in the rawBytes regardless of encoding. `keyDetails` already specifies encoding, and I'd rather not force that all rawBytes are of a single encoding type.

**Comment by Hayden-IO** [comment]
cc @woodruffw since we were chatting on the other issue

**Comment by Hayden-IO** [comment]
I guess this is mostly a question for how clients want to handle this. I assume the workflow will go something like:
* Look at keyDetails for the encoding
* Parse rawBytes accordingly
* Determine if logID matches <- Either take the digest of rawBytes, or reconstruct the key as SPKI and take the digest. Either option seems fine - Cosign does the latter - https://github.com/sigstore/cosign/blob/a8f57b66e8ad96ba13541dadc3bd47ae0c9a0c67/pkg/cosign/tlog.go#L76

**Comment by kommendorkapten** [comment]
> or reconstruct the key as SPKI and take the digest

I think that is the safest option, as there may be some risk of a key being transformed to another encoding, and that could possibly break a client. As the way the comment is written now, it depends on the key being delivered to the client in the same encoding it was created, which I think is a bit fragile. Specify the format in the protobuf comment and update any client code would solve this.

**Comment by woodruffw** [comment]
> * or reconstruct the key as SPKI and take the digest

This is also what sigstore-python does:

https://github.com/sigstore/sigstore-python/blob/6d63b6e63d3bbd3ee87817b6a2f04cdc98324723/sigstore/_utils.py#L122-L133

**Comment by Hayden-IO** [comment]
Thanks y'all, so I'll go forward with updating the documentation and fixing the RSA key ID in staging.
