### ISSUE TITLE
[bug] Staging snapshot and timestamp does not push all changes in staged/ folder

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#782]
**Description**

The staging snapshot and timestamp uploads files that were changes (i.e. the uploads the new published repository), but does NOT upload history that the staged/ files were deleted. 

This was a limitation of how the workflow worked - it uploaded changed files, downloaded them and pushed a PR with the changes. The changes did NOT include file deletions.

See this run:
https://github.com/sigstore/root-signing/actions/runs/4615379133/jobs/8159204123

1. The `publish` step performs the publish and you can see that the staged folder is deleted.
![image](https://user-images.githubusercontent.com/5194569/230127831-29704473-073e-47cd-a3dc-3820867d3b22.png)
2. We upload the repository folder with the new files.
3. We download the repository folder with the new files on to the EXISTING state.
4. We create the PR.

Step (2) and (3) do not keep track of the staged metadata.

I think I should instead upload the git patch and apply that in the PR creation job.

cc @kommendorkapten thank you for finding this!

**Comment by asraa** [comment]
BTW: no affect on the actual GCS sync, we only sync the repository sub-folder:
https://github.com/sigstore/root-signing/actions/runs/4619672892/jobs/8168728616

**Comment by joshuagl** [comment]
I was reading this thinking "we should pass around patches" and pleased to see the same suggestion made 😄 

`git format-patch` and `git am` seem like useful commands here.
