### ISSUE TITLE
Updating references to the GCS buckets

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#795]
**Description**

We're switching clients over to the CDN. List of places to update:

- [x] Probers - https://cs.github.com/sigstore/sigstore-probers/blob/64665a694f3f277b86f3c20f944f23a8907c3f98/.github/workflows/prober-staging.yml?q=org%3Asigstore+tuf-root-staging#L33-L35
- [x] https://cs.github.com/sigstore/sigstore-probers/blob/64665a694f3f277b86f3c20f944f23a8907c3f98/.github/workflows/reusable-prober.yml?q=org%3Asigstore+sigstore-tuf-root#L31 - reusable prober
- [x] https://cs.github.com/sigstore/sigstore-python/blob/6d63b6e63d3bbd3ee87817b6a2f04cdc98324723/sigstore/_internal/tuf.py?q=org%3Asigstore+tuf-root-staging#L49-L50 - Update staging and prod buckets to CDN for Python client
- [x] README for Java - https://cs.github.com/sigstore/sigstore-java/blob/e85be5485dc2103d02e556d28403adf791f5559a/sigstore-java/src/main/resources/dev/sigstore/tuf/README.md?q=org%3Asigstore+tuf-root-staging#L9-L13
- [x] GitSign tests - https://cs.github.com/sigstore/gitsign/blob/f9e70b562d31dd1201d671943fbd864812447007/.github/workflows/e2e.yaml?q=org%3Asigstore+tuf-root-staging#L106-L107
- [x] https://docs.sigstore.dev/cosign/keyless/#usage - Staging documentation, update `initialize` command
- [x] sigstore/sigstore changes ([ongoing](https://github.com/sigstore/sigstore/pull/1089))
- [x] Update Cosign with latest sigstore/sigstore release
- [x] https://cs.github.com/sigstore/fulcio/blob/ba297919336d6cee0f3e9c82bc01e5f909e21e1c/README.md?q=org%3Asigstore+sigstore-tuf-root#L44 - Fulcio docs
- [x] https://cs.github.com/sigstore/sigstore-rs/blob/4d2629cd2b0e91c3437c1b29d2ea52b3233d52ff/src/tuf/constants.rs?q=org%3Asigstore+sigstore-tuf-root#L24-L26 - sigstore-rs client
- [x] https://cs.github.com/sigstore/sigstore-js/blob/da0bfd73a9638a98fa30a11b817a7faa83499353/src/tuf/index.ts?q=org%3Asigstore+sigstore-tuf-root#L26 - sigstore-js client
- [x] https://cs.github.com/sigstore/docs/blob/768239a98525a8ee7d0228f921a2e2651daa8cc4/content/en/cosign/installation.md?q=org%3Asigstore+sigstore-tuf-root#L133 - installation docs
- [x] https://cs.github.com/sigstore/cosign/blob/a8f57b66e8ad96ba13541dadc3bd47ae0c9a0c67/cmd/cosign/cli/initialize.go?q=org%3Asigstore+sigstore-tuf-root#L35 and https://cs.github.com/sigstore/cosign/blob/a8f57b66e8ad96ba13541dadc3bd47ae0c9a0c67/doc/cosign_initialize.md?q=org%3Asigstore+sigstore-tuf-root#L44- cosign docs
- [x] https://cs.github.com/sigstore/root-signing/blob/20c5e95c2bd360ef6c664a9cdaf245befd2f66dc/.github/workflows/validate.yml?q=org%3Asigstore+sigstore-tuf-root#L34 - root-signing validation prober
- [x] https://github.com/sigstore/policy-controller/blob/a4891f0efb52855fe055a4e0d2c73823d3abdf4e/pkg/apis/policy/v1alpha1/trustroot_types.go#L103 - policy-controller docs

**Comment by bobcallaway** [comment]
PRs:

https://github.com/sigstore/sigstore/pull/1089
https://github.com/sigstore/sigstore-python/pull/609
https://github.com/sigstore/sigstore-rs/pull/251
https://github.com/sigstore/sigstore-js/pull/402
https://github.com/sigstore/sigstore-java/pull/419
https://github.com/sigstore/gitsign/pull/285
https://github.com/sigstore/root-signing/pull/796
https://github.com/sigstore/sigstore-probers/pull/47

Docs:

https://github.com/sigstore/cosign/pull/2891
https://github.com/sigstore/sigstore-java/pull/418
https://github.com/sigstore/fulcio/pull/1108
https://github.com/sigstore/policy-controller/pull/718
https://github.com/sigstore/docs/pull/124

**Comment by Hayden-IO** [comment]
One thing I realized, cosign caches the remote address locally, so we might want to add something like "if local remote == prod gcs bucket, update to cdn"

**Comment by asraa** [comment]
You could treat it like an alias - like make a helper `GetRemoteFromCache` that does that conversion internally

https://github.com/sigstore/sigstore/blob/5c6a551f22ad23cd8ebe171c55305e0f31c46093/pkg/tuf/client.go#L325

**Comment by Hayden-IO** [comment]
Reopening to track fixing the on-disk gcs reference
