### ISSUE TITLE
Prerequisites for verification with old targets

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#80]
Context: https://github.com/sigstore/cosign/issues/1273

To support verifying old targets, we will need to enable consistent snapshots to persist versioned targets and snapshots.

- [ ]  Enable consistent snapshots in Sigstore root - I have tested locally with cosign and don't see any issues with consistent snapshots and versioned target names.
- [ ] Confirm that versioned targets.json and all targets are in Sigstore's root, synced to GCS bucket - This step should be a no-op. I have tested locally that when a new target is added to `staged/targets` and the targets metadata is regenerated, we see both a versioned "x.targets.json" and the target be added to the `targets` folder as `hash.target.ext` alongside the previous target. 
- [ ] Stop generating snapshot frequently. I don't see value  in generating snapshots as frequently as timestamps. Snapshots can be generated when targets are updated. If we don't reduce this and separate this from timestamp generation, as we increase timestamp generation frequency, storage costs will increase.
- [ ] Generate timestamp more frequently - Optional for now as we aren't frequently updating targets
- [ ] Automate checking in PR for timestamp generation - Optional, but highly recommended if we increase timestamp generation to daily or less than daily

Lemme know if you have any questions or concerns with any of these bullet points. 

@asraa @bobcallaway @dlorenc

**Comment by asraa** [comment]
> persist versioned targets and snapshots.

Should we also add custom metadata to tag target names? Or how do we expect multiply supported fulcio root CAs in one target file to differ in name?

e.g. cosign fetches all targets with custom metadata tagged "sigstore: fulcio" rather than hardcoded names?

**Comment by Hayden-IO** [comment]
Is there good support for custom metadata tags currently? If so, then yea, I think we should make this change. It'd be cleaner than requiring target names and using regex. If there isn't good support for custom metadata, we could make do with regex for now.

Btw, should we put this under a separate issue? This seems more about better support for rotation of a target (attempting to verify with both the current and new target) than how to verify an old target.

**Comment by Hayden-IO** [comment]
No longer needed, #93 covers the key items from this
