### ISSUE TITLE
Change timestamp/snapshot expiry

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#860]
**Description**

Currently, the timestamp expires every 2 weeks. If there is a key compromise, it would take clients at most 2 weeks to pick up the new key material. I propose we lower the expiration to 1 week, and consider lowering it more.

The impact of this change:
* Clients need to more frequently go online to fetch the latest timestamp
* Slight storage increase, since we'll generate snapshots (which are consistent, and we keep a history of previous snapshots) more frequently
* Small network egress increase for the GCS/CDN TUF repo, since clients will request timestamps more frequently

This also requires updating the snapshot/timestamp GHA to run more frequently. It currently runs every week, so we would need to have it run every 3-ish days.

We also should reduce the time that metadata sits in the preprod bucket before being synced to prod. Currently we wait 3 days, then sync to prod. This would mean that a timestamp is generated, sits in the bucket for 3 days, then is valid for only 4 more days. We can reduce this time to 24 hours.

cc @bobcallaway @asraa @kommendorkapten Thoughts?

**Comment by bobcallaway** [comment]
+1 to the shift to a week. On a first thought, 72 hours feels like a decent tradeoff as a long-term target for the timestamp duration.

**Comment by asraa** [comment]
sgtm, we meant to reduce eventually to about a day if we were confident about it :) reducing to a week is a good step now.

(Usually a day is typical for timestamp duration)

**Comment by asraa** [comment]
Would you keep the expiration of the snapshot as is?

Snapshots don't need to be regen'd when timestamps are signed FYI

**Comment by Hayden-IO** [comment]
Yea, I was thinking about that too. I don't think we need to update the expiration of the snapshot, it's just a little more work to split out the GHA.

**Comment by asraa** [comment]
Yeah, I agree - plus the timestamp files aren't "consistent" so you don't have any added storage if you just reduce the timestamp time and keep snapshot as is

**Comment by kommendorkapten** [comment]
This sounds all good to me, I'm in favour of lowering it to a week now, then consider lower it even more.

**Comment by bobcallaway** [comment]
sounds like we have consensus!

**Comment by Hayden-IO** [comment]
Fantastic, I'll start the changes. Thanks all!
