### ISSUE TITLE
Add logging for root signing flows

### ISSUE THREAD

**Issue by lkatalin** [sigstore/root-signing#887]
To help with debugging, auditing, etc.

**Comment by Hayden-IO** [comment]
Are there particular areas to log that would be helpful?

**Comment by asraa** [comment]
Finding a way to see PAT attribution :)

**Comment by lkatalin** [comment]
Maybe some timestamps in the GHA workflows also, unless I missed them.

**Comment by jku** [comment]
We have changed just about everything that does logging in the past week-- would be very interested in specific improvement suggestions

**Comment by Hayden-IO** [comment]
Closing as we didn’t have any specific suggestions and this is not outdated.
