### ISSUE TITLE
Timestamp update did not trigger main to preprod sync

### ISSUE THREAD

**Issue by lkatalin** [sigstore/root-signing#888]
#884 did not trigger a main to preprod sync. This is strange because:

- #884 updates `timestamp.json`, the path for which is `https://github.com/sigstore/root-signing/.../repository/repository/timestamp.json`
- The [sync main to preprod file](https://github.com/sigstore/root-signing/blob/f43aa701b3775d0b6f4162eace45c19a6a6241c5/.github/workflows/sync-main-to-preprod.yml#L25) defines that a sync should occur when any file under `repository/repository` is changed

**Comment by asraa** [comment]
The reason may be because a bot merged the PR: https://github.com/sigstore/root-signing/pull/884

and usually GitHub Actions prevents Actions from triggering Actions (to prevent automatic workflow recursion)

See this related issue: https://github.com/sigstore/root-signing/issues/507

**Comment by lkatalin** [comment]
Oh, I didn't know that! Thank you @asraa , this may be the problem.

**Comment by Hayden-IO** [comment]
@asraa, I have configured the workflow to use the secret - https://github.com/sigstore/root-signing/blob/f43aa701b3775d0b6f4162eace45c19a6a6241c5/.github/workflows/stable-timestamp.yml#L97

Do you have any guesses why it merged with the bot rather than the PAT?

**Comment by Hayden-IO** [comment]
Could it be that a PAT can't be reused with a workflow created after the PAT's date?

@cpanato any guesses?

**Comment by asraa** [comment]
That's the PAT that creates the PR, not merges it: https://github.com/sigstore/root-signing/blob/f43aa701b3775d0b6f4162eace45c19a6a6241c5/.github/workflows/reuseable-snapshot-timestamp.yml#L26

so I don't think that is a reason for why this is happening.

**Comment by asraa** [comment]
It's true that the review [workflow](https://github.com/sigstore/root-signing/blob/f43aa701b3775d0b6f4162eace45c19a6a6241c5/.github/workflows/scripts/review-pull-request.sh#L58C17-L58C29) is using the token passed in [too](https://github.com/sigstore/root-signing/blob/f43aa701b3775d0b6f4162eace45c19a6a6241c5/.github/workflows/review-snapshot-timestamp.yml#L34), but is `GITHUB_TOKEN` override-able? Maybe it should just be `TOKEN`.

I'm guessing that's the problem. GITHUB_ vars are usually not override-able.

**Comment by Hayden-IO** [comment]
FWIW, https://github.com/sigstore/root-signing/pull/880 looks identical to https://github.com/sigstore/root-signing/pull/884, in that a bot merged the PR

**Comment by asraa** [comment]
To add the logging for the PAT attribution, maybe the scripts can each `gh auth login`. I'm not sure though. Otherwise, it the PRs look identical. It just matters what underlying PAT was used.

**Comment by asraa** [comment]
> FWIW, https://github.com/sigstore/root-signing/pull/880 looks identical to https://github.com/sigstore/root-signing/pull/884, in that a bot merged the PR

I haven't seen a commit trigger the sync job since a month ago: https://github.com/sigstore/root-signing/actions/workflows/sync-preprod-to-prod.yml?page=9 (and that wasn't a review bot commit)

**Comment by Hayden-IO** [comment]
It was this workflow that didn't trigger - https://github.com/sigstore/root-signing/actions/workflows/sync-main-to-preprod.yml

Which seems to say that it is running after a commit is pushed by the bot

**Comment by asraa** [comment]
Hmmm maybe there was an underlying GitHub Actions change?

**Comment by Hayden-IO** [comment]
One other weird thing is I see no checkmark next to the PR after merge like I normally do:

<img width="932" alt="Screenshot 2023-07-24 at 8 38 39 AM" src="https://github.com/sigstore/root-signing/assets/8418760/d6495b21-1f83-4173-9d53-b48f5b96bd2b">

**Comment by Hayden-IO** [comment]
I wonder if it was simply a GHA temporary failure. Let's see if today's snapshot/timestamp go through smoothly, and I'll kick off another timestamp-only generation after that.

I think a simple fix is to run the sync main to preprod periodically too.

**Comment by asraa** [comment]
Yeah, i wonder if GHA was down at the time...

**Comment by Hayden-IO** [comment]
Chatted with @bobcallaway, plan is:

* Wait to see if the snapshot/timestamp PR gets merged and the sync to preprod kicks off
* I'll manually kick off the workflow for timestamp only, wait for the PR to get merged and see if preprod kicks off
* If it doesn't, we'll regenerate the CI tokens and update the secrets in this repo and try again
* If that doesn't work...ask someone from GH?

**Comment by Hayden-IO** [comment]
^ Whoops, that's funny, I guess the issue title matched the regex

**Comment by Hayden-IO** [comment]
https://github.com/sigstore/root-signing/actions/runs/5648272063/job/15300136293 - Successful run

Going to kick off timestamp now

**Comment by Hayden-IO** [comment]
No issue with the latest run - https://github.com/sigstore/root-signing/actions/runs/5649273862

My guess is it was a random GHA failure.

**Comment by lkatalin** [comment]
> No issue with the latest run - https://github.com/sigstore/root-signing/actions/runs/5649273862
> 
> My guess is it was a random GHA failure.

For my edification, when I look at the [main to preprod workflows](https://github.com/sigstore/root-signing/actions/workflows/sync-main-to-preprod.yml), it looks like the ones triggered automatically all say "Update Snapshot and Timestamp" (referring to PRs on this repo merged by the bot), but the PRs we weren't sure are triggering the sync are Timestamp-only. I don't see those in the [sync workflows](https://github.com/sigstore/root-signing/actions/workflows/sync-main-to-preprod.yml). What am I missing or misreading?

**Comment by Hayden-IO** [comment]
It's cause the title wasn't updated to be different - https://github.com/sigstore/root-signing/blob/main/.github/workflows/reuseable-snapshot-timestamp.yml#L203

Easy enough fix

**Comment by cpanato** [comment]
if we use a the default injected github token that will not trigger anything, we need to use a PAT for that
but looks like that was not the reason :)

**Comment by hectorj2f** [comment]
We are experiencing this issue again! Re-opening!

**Comment by lkatalin** [comment]
I read the executed workflows slightly wrong and thought this issue was at fault again, but in today's incident, the sync did occur. The actual problem was that we need to sync more frequently (see #893 ). I think we can close this issue again.
