### ISSUE TITLE
Better error handling of gh api failures

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#900]
**Description**

In https://github.com/sigstore/root-signing/blob/main/.github/workflows/scripts/review-pull-request.sh, we should handle whenever `gh api` fails and pass this status to https://github.com/sigstore/root-signing/blob/main/.github/workflows/review-snapshot-timestamp.yml

**Comment by jku** [comment]
closing -- I'm sure there are still cases where error handling is not stellar but these particular workflows are no longer an issue
