### ISSUE TITLE
Script to verify latest root against v1 root

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#915]
**Description**

This is useful for those who want to verify an embedded root against the original, independently verifable root.

Need `set_ecdsa` for handling deprecated key format.

**Comment by asraa** [comment]
There's one in this repo that already exists: https://github.com/sigstore/root-signing/blob/main/tests/client-tests/main.go

**Comment by Hayden-IO** [comment]
perfect!
