### ISSUE TITLE
[V8 signing] Update key type to "ecdsa"

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#923]
**Description**

Key type is currently "ecdsa-sha2-nistp256", which is not spec compliant. go-tuf has now been updated to the spec compliant "ecdsa", with support for both key types currently (https://github.com/theupdateframework/go-tuf/blob/master/pkg/keys/ecdsa.go#L23-L26). For the v8 signing, we should update the key type.

**Comment by asraa** [comment]
Just FYI for key updates you will need to perform the same double-key setup we did to migrate keys to a newer format before. This will require doubling the keys and having 10 sigs, old and new, on the root.

**Comment by Hayden-IO** [comment]
Inspiration PR: https://github.com/sigstore/root-signing/pull/617/

**Comment by Hayden-IO** [comment]
Done with v9!
