### ISSUE TITLE
Improve tuftool install time

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/root-signing#924]
**Description**

tuftool takes very long to install, causing https://github.com/sigstore/root-signing/blob/main/.github/workflows/tuf_client_tests.yml to take ~10 minutes to run.

@woodruffw, did you have any suggestions on how to improve rust app install time? I know we ran into this in protobuf-specs too.

**Comment by asraa** [comment]
You could try github actions cache, or you can also explore use-tool-cache.

**Comment by woodruffw** [comment]
+1 to caching; I can also take a look later today or tomorrow and see if I can identify any major pain spots. Often times with Rust the main "trick" is just deleting dependencies to speed things up 🙃
