### ISSUE TITLE
Root/Targets Signing v3 

### ISSUE THREAD

**Issue by asraa** [sigstore/root-signing#93]
**Description**

Tracking issue for all the changes we need for our v3 root signing enhancements. The v2 root will expire on 2022-05-11. Let's aim to re-sign in February. 

Changes to do in root/targets:
- [x] Reduce root/target expiration to 4 months rather than [6](https://github.com/sigstore/root-signing/blob/03e99f8018ee1189ef9984f9ef09569808a810f5/cmd/tuf/app/init.go#L95)
- [x] Rotate out one key-holder TBD 
- [x] Create a test setup with >1 YubiKey 
- [x] Add custom metadata indicated usage/lifetime/version of the target metadata for the Rekor/Fulcio/CT key
- [x] Add a revocation delegation @haydentherapper 
- [x] Enable consistent snapshots (https://github.com/sigstore/root-signing/issues/80)
- [ ] (Optional?): Start including the HSM certs into the root metadata
- [x] #161 

Changes in snapshot/targets:
- [x] Increase snapshot re-signing to... 3 weeks? (and on delegation changes)
- [ ] Decrease timestamp signing WITH automatic merging

Perhaps there are other changes in delegations but they don't need to be signed by the root/targets so I'm not ass worried about them.

cc @dlorenc @haydentherapper

**Comment by Hayden-IO** [comment]
Great list! 

>  Increase snapshot re-signing to... 3 weeks? (and on delegation changes)

I agree with this. Maybe even less frequent, since we are rarely updating targets? Something to note: I was looking through https://theupdateframework.io/faq/ and it mentioned having frequent regeneration of the snapshot, as frequently as the timestamp. I don't see a purpose to having a bunch of versioned snapshots that we have to indefinitely persist, especially given how infrequently the targets are changing. Might be worth discussing if the FAQ's guidance should be updated based on your usage of TUF.

Other task:

What do you think about also adding some alerting for failed operations? For example, filing an issue if a GCS sync fails, or if automatic merging fails? Otherwise, this could cause an "outage" where clients can't fetch the latest signed metadata.

**Comment by mnm678** [comment]
> Something to note: I was looking through https://theupdateframework.io/faq/ and it mentioned having frequent regeneration of the snapshot, as frequently as the timestamp. I don't see a purpose to having a bunch of versioned snapshots that we have to indefinitely persist, especially given how infrequently the targets are changing. Might be worth discussing if the FAQ's guidance should be updated based on your usage of TUF.
> 

I think this advise is for implementations where snapshot changes more frequently. As explained in #7 of that faq, if snapshot is updated less frequently, it can expire less frequently, especially if it's possible to use an offline key to sign snapshot.

**Comment by asraa** [comment]
> Maybe even less frequent, since we are rarely updating targets?

But rekor shards and delegations will be updated intermittently, which snapshot will sign off on (right?), so I think this should be done semi-frequently. O(weeks)

**Comment by Hayden-IO** [comment]
Thanks @mnm678, that makes sense! 

@asraa , good point, I didn't realize the snapshot would contain all of the delegations' files too. So yea, maybe every few weeks, and we can adjust during the next root signing if we find we need it to be more frequent or less. 3 weeks would be ~17 snapshots per year, every 4 weeks would be 13, which seems reasonable.

**Comment by Hayden-IO** [comment]
@asraa, did you have any updates on this?

**Comment by asraa** [comment]
Hey! I think my first next step is to "gently" update go-tuf: I think we're going to have some roadblocks in delegations with that (since it might break our auto-updates because one delegation is expired), so I'll try my best to match what will happen.

I think at this point it's best to not be too ambitious with my init from config, so I'm going to keep the scripts as is and add a new delegation for v3. I'll make some gentle PRs here, but will do the go-tuf updates on my test root branch first, where we can test out an update later this week.

**Comment by Hayden-IO** [comment]
@asraa , added #161 to the list of tasks

**Comment by asraa** [comment]
v3 is done, a root keyholder was rotated in v4.
