### ISSUE TITLE
Monitoring for metadata expiration?

### ISSUE THREAD

**Issue by trishankatdatadog** [sigstore/root-signing#96]
**Question**

Do we have monitors/pagers in place to make sure that root/timestamp/snapshot/targets metadata are renewed before actually expiring in production? Otherwise, we risk accidentally running into the old "forgot to renew TLS cert in prod..."

**Comment by asraa** [comment]
We should! Even a slack app alert would help. WDYT?

**Comment by joshuagl** [comment]
Perhaps a GitHub Action which parses metadata, checks expiry, and files an Issue when the expiration is close?

**Comment by asraa** [comment]
I LOVE THAT JOSHUA! Assigning, love it love it.

**Comment by asraa** [comment]
@priyawadhwa set up GCP monitoring

* Cron to Slack would be GA blocker. will be a fallback eventually
* Ideal state would be cron talks to GCP monitoring so that pagers can get these alerts too
